### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#1]
Arch Linux Support

I will support your application in Arch Linux.

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find Newaita under the name [newaita-icons-git](https://aur.archlinux.org/packages/newaita-icons-git/) in the **AUR**:

`$ aurman -S newaita-icons-git`

PS: I added your donation link in package description.

**Comment by cbrnix** [comment]
Oh, thank you! I am use arch)

**Comment by cbrnix** [comment]
Dit it! One more thank you)

**Comment by cbrnix** [comment]
I changed the structure of the theme icons. Perhaps this will cause problems? Is it more convenient to leave it so or make a dark version in a separate branch?
