### ISSUE TITLE
Evolution on Fedora Crashing

### ISSUE THREAD

**Issue by Aiduss** [cbrnix/Newaita#10]
I think because of some missing icons Evolution is crashing sometimes (for example when i open some email that has not loaded external content message)
Maybe this LightBulb icon : https://imgur.com/a/RVSYjEG

Same crash applies for other gnome apps on Fedora 28.

**Comment by cbrnix** [comment]
it is unlikely that the reason for the fall of the evolution may be the absence or presence of icons. Moreover, in Arch/Manjaro this is not observed.
Look at the trigger output and the actions that lead to the crash

**Comment by Aiduss** [comment]
Terminal output : Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/eximus/.icons/Newaita-dark/mimetypes/32/image.svg: Error opening file /home/eximus/.icons/Newaita-dark/mimetypes/32/image.svg: No such file or directory (g-io-error-quark, 1)
Aborted (core dumped)

**Comment by Aiduss** [comment]
Thanks and take your time :)  Your work is awesome!
