### ISSUE TITLE
[Icon Request] Speedcrunch

### ISSUE THREAD

**Issue by Shatur95** [cbrnix/Newaita#100]
| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Speedcrunch`| `speedcrunch` | `speedcrunch.desktop` | ![icon](https://bitbucket.org/heldercorreia/speedcrunch/raw/c0fc9c68d292030e92cd952f27e83b97a61aa2b8/gfx/speedcrunch.svg) |

**Description:** SpeedCrunch is a high-precision scientific calculator. It features a syntax-highlighted scrollable display and is designed to be fully used via keyboard. Some distinctive features are auto-completion of functions and variables, a formula book, and quick insertion of constants from various fields of knowledge. It is available for Windows, OS X, and Linux in a number of languages.

**Links:** [Link](https://bitbucket.org/heldercorreia/speedcrunch/src/master) to the program Bitbucket repository. [Link](https://bitbucket.org/heldercorreia/speedcrunch/src/master/gfx/speedcrunch.svg) to the original icon in repo.

**Comment by cbrnix** [comment]
Added

**Comment by Shatur95** [comment]
Looks awesome, thank you!
