### ISSUE TITLE
Icons not working in new Plasma 5.16

### ISSUE THREAD

**Issue by freefreeno** [cbrnix/Newaita#102]
I tried the new Plasma when it was in testing stage and the Newaita icons would not work and today after the update the same thing is happening. I hate the new plasma. They have nearly turned me against with this one. Its awful. Colors are not even close to being the same either.
![Screenshot_20190612_183412](https://user-images.githubusercontent.com/41884680/59393339-c68c0800-8d40-11e9-921b-5b4d56526884.png)

NEW NEVER HAD ANYTHING DONE TO IT.
Here is a pretty close list. If it has comment it is just section not icon.. Anything without comment is missing for sure.

#Power management
activity settings

#Account Details
user manager

#Window management
Task switcher

#Desktop Behavior
Virtual desktops
Activities
Touch Screen
Screen Edges
Desktop effects

#Network
#Settings
Windows Shares

#Application Style
Application Style
Window Decorations

#Workspace theme
Workspace theme
Plasma theme
cursors

#Look and Feel
look and feel

**Comment by cbrnix** [comment]
Yes, they introduced again new icons. In the near future will have to do a revision and add. Finish the topic becomes more difficult. I do not have time for updates XD

**Comment by freefreeno** [comment]
I was just letting you know. I love your icons and I really hope you can find the time to fix them up. My colors are not correct anymore at all and the really I do not like the entire update myself. I have stuff to fix on my themes at kde store also because of the update.

**Comment by cbrnix** [comment]
check maybe something forgot (I have a stable KDE)

**Comment by freefreeno** [comment]
Workspace theme and virtual desktops I think. I was in hurry. I will check again later.

**Comment by freefreeno** [comment]
cursors

**Comment by cbrnix** [comment]
To see what icons the breeze is responsible for. It is very difficult to blindly

**Comment by cbrnix** [comment]
> cursors,window decorations,task switcher,windows shares
> I think that may be it

Could you make a screenshot of the icons that are missing? I have the latest icons Breeze, I will look into them

**Comment by cbrnix** [comment]
> cursors,window decorations,task switcher,windows shares
> I think that may be it
I added this :) My plasma has been updated

**Comment by freefreeno** [comment]
I will check then. I know you do not want to hear this but during my reprieve from your icons and while I was using Breeze icons I have grown to like the smaller icons at the top of Dolphin file manager and I also have had at least one person say that they prefer the smaller icons in that location also. I personally was heartbroken when you removed the colored icons from there but I have learned to like the non colored icons. I also have noticed something that is annoying to me. You know how Plasma shades the icons sometimes???? I don't know how to explain this but when some of your icons are shaded like that they get this look like they almost look dirty.Kinda like they have a brown tint or something. I believe it is because of the transparency added to your icons. The worst ones at doing this is the aqua because they are the lightest. I will check the icons and let you know.
