### ISSUE TITLE
[Icon Request] Riot

### ISSUE THREAD

**Issue by gregorydk** [cbrnix/Newaita#109]
`riot-web`

https://about.riot.im/

Icon exists but it needs a refresh.

![riot-web](https://user-images.githubusercontent.com/7804464/59509545-9d3eb980-8eb1-11e9-9f8a-7ee006624047.png)

**Comment by cbrnix** [comment]
Already available

**Comment by gregorydk** [comment]
@cbrnix Yes, it is already available, but the icon has changed design and colours. It needs an update.

**Comment by cbrnix** [comment]
> @cbrnix Yes, it is already available, but the icon has changed design and colours. It needs an update.

Restyled
