### ISSUE TITLE
[Request] add ".cbz" mime-type icon

### ISSUE THREAD

**Issue by demoy** [cbrnix/Newaita#111]
.cbz is the extension use to indicate a comic book, it just a zip archive containing images (https://en.wikipedia.org/wiki/Comic_book_archive). It's recognize by common document viewers (evince, okular, calibre, etc).

Here are the paths specific file names used by papirus for reference:
application-vnd.comicbook+zip.svg (actual file, all the rest below sym link to it)
application-x-cbz.svg
application-x-cbr.svg
application-x-cb7.svg
application-x-cbt.svg
application-x-cba.svg

**Comment by cbrnix** [comment]
Added

**Comment by demoy** [comment]
Thanks, cute icons!
