### ISSUE TITLE
Special folder icons aren't distinguishable with low sizes.

### ISSUE THREAD

**Issue by ripefig** [cbrnix/Newaita#115]
I'd recommend only showing the folder emblems at low sizes - instead of showing the full folder icon (maybe make them them all vanilla/brown to make it clear they are folders). So the Downloads folder should just be a downward pointing arrow at low sizes.

Compre with Breeze. All folder icons are easily distinguishable at low sizes in Breeze, but with Newaita you have to really squint to tell them apart.

Newaita:
![image](https://user-images.githubusercontent.com/45201036/63390140-b0409f00-c3b6-11e9-9094-a13b69a74445.png)

Breeze:
![image](https://user-images.githubusercontent.com/45201036/63390193-debe7a00-c3b6-11e9-99f1-8854b7e6c2dd.png)

**Comment by cbrnix** [comment]
Icons 16 sizes in development. They will be monochrome, but a little later

**Comment by ripefig** [comment]
@cbrnix. I don't think it's a good idea to make small all small icons monochrome (black/white/grey) unless they are symbolic or action icons. So I think KDE made a bad design decision by making folder icons and mimes monochrome. You zoom out and it's as if you are using a new icon theme - which is completely illogical.

The reason I mentioned KDE was because they used simpler shapes for small icons, which is a good idea. But making icons monochrome just because they are small is very bad.

BTW, the icons in my screenshot are size 22, not 16.





there is any need for 16 sizes to be monochromem unless they are status/action icons, so if you plan on doing them all monochrome

**Comment by cbrnix** [comment]
In principle, I can make small icons simply consist of the same symbols (video, music, etc.) as the large ones, just by painting them. But you mentioned size 22 here. Apparently, you have to do them for this
