### ISSUE TITLE
[Icon Request] Icon for "R" (r-base-core).

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#118]
Please add an icon for "R". The icon name is rlogo_icon and is included in package r-base-core. You already have an icon for "R Studio", but "R" is a prerequisite for "R Studio", and it is always installed along with "R Studio".

Also see https://cran.r-project.org/...

![image](https://user-images.githubusercontent.com/19394936/63736746-32ffa900-c852-11e9-9176-29cd2d510a1b.png)

**Comment by cbrnix** [comment]
rlogo_icon added yesterday

**Comment by PJSingh5000** [comment]
Very nice!
Thank You!
