### ISSUE TITLE
[Icon Request] Icon for mkusb and guidus

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#119]
Please add icon(s) for mkusb and guidus...

https://help.ubuntu.com/community/mkusb

Here is an example from /usr/share/icons/hicolor/scalable/apps/mkusb.svg ...

![mkusb](https://user-images.githubusercontent.com/19394936/63737179-89b9b280-c853-11e9-89ee-6296c5e0fed8.png)

**Comment by cbrnix** [comment]
Added

**Comment by PJSingh5000** [comment]
A true work of art!
Thank you.
