### ISSUE TITLE
[Icon Request] Icon for Alternatives Configurator (galternatives)

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#121]
Please add an icon for "Alternatives Configurator" (galternatives) application.

According to the project page, "G Alternatives is a tool that provides a simple GUI interface for `update-alternatives`, allowing system administrator to select which programs provide specific services for the user by default. "

The current icon, which looks like an "App Store" grocery bag (located at `/usr/share/icons/hicolor/48x48/apps/galternatives.png`), doesn't seem to capture the intent of the tool. 

![galternatives](https://user-images.githubusercontent.com/19394936/64136005-82972500-cdbc-11e9-8315-ae370ebb4162.png)

Hopefully, you can design an icon for Newaita that better captures the purpose of this application!

There is an `*.svg` version of the current icon, located at `/usr/share/icons/hicolor/scalable/apps/galternatives.svg`, and the deb package is `galternatives` (https://packages.ubuntu.com/disco/galternatives).

The official project page is located at https://github.com/debiancn/galternatives.

Here is a screen shot of the application running, to give you a sense of what it does: if you have multiple applications installed that do the same thing, galternatives lets you set which application should be used by the system as the default app.

![galternatives](https://user-images.githubusercontent.com/19394936/64136300-a9eef180-cdbe-11e9-9678-d1fbde01f339.png)

**Comment by cbrnix** [comment]
Added. Did what makes me association)

**Comment by PJSingh5000** [comment]
Clever!
Thanks!

![image](https://user-images.githubusercontent.com/19394936/64211300-be40f600-ce73-11e9-98d3-5d39ffbf7a4e.png)
