### ISSUE TITLE
[Icon Request] zerobrain studio icon

### ISSUE THREAD

**Issue by ripefig** [cbrnix/Newaita#123]
`zbstudio`

![zbstudio](https://user-images.githubusercontent.com/45201036/64388230-1ed45c80-d047-11e9-8b33-462dd1802c3d.png)

**Comment by btd1337** [comment]
@ripefig why u don't agroup your request in a single issue? Like here: https://github.com/cbrnix/Newaita/issues/120

**Comment by btd1337** [comment]
@ripefig why u don't agroup your requests in a single issue? Like here: https://github.com/cbrnix/Newaita/issues/120

**Comment by cbrnix** [comment]
Done
