### ISSUE TITLE
[Icon Request] Please add an icon for PDF Arranger

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#126]
PDF Arranger is an app to merge, split and re-arrange pages from PDF documents.
The Ubuntu package is `pdfarranger`.
The project page is on GitHub: https://github.com/jeromerobert/pdfarranger.

This is the current icon, located at `/usr/share/icons/hicolor/256x256/apps/pdfarranger.png`.
![pdfarranger](https://user-images.githubusercontent.com/19394936/64660103-dd5bfc80-d40c-11e9-8d8a-e885fe39f26b.png)

**Comment by cbrnix** [comment]
Done
