### ISSUE TITLE
[Icon Requests] for Meld Application's Buttons

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#127]
The Meld application has three large buttons with actions:
(1) File comparison
(2) Directory comparison
(3) Version control view

There are issues with the icons for buttons (1) and (3) above. Please see the screenshots of Meld posted at the end of this issue.

---

### (1a) Need new larger colored icon for "File comparison"  button

We are missing the **48px `document-new.svg` _colored_** icon in Newaita. Because this is a large icon, the new icon must be _colored_, and must _not_ be monochromatic symbolic style.
```
/usr/share/icons/Newaita/actions/48/document-new.svg
```

### (1b) Need symbolic-links `filenew.svg` --> `document-new.svg`

We are also missing the **`filenew.svg`** symbolic-links. This doesn't impact Meld, but may be used by other applications.
````
/usr/share/icons/Newaita/actions/16/filenew.svg (should be link to document-new.svg)
/usr/share/icons/Newaita/actions/22/filenew.svg (should be link to document-new.svg)
/usr/share/icons/Newaita/actions/24/filenew.svg (should be link to document-new.svg)
/usr/share/icons/Newaita/actions/32/filenew.svg (should be link to document-new.svg)
/usr/share/icons/Newaita/actions/48/filenew.svg (should be link to document-new.svg)
````

---

### (3a) Need new larger colored icon for "Version control view" button

We are also missing the **48px `meld-version-control.svg` _colored_** icon in Newaita. Because this is a large icon, the new icon must be _colored_, and must _not_ be monochromatic symbolic style.
````
/usr/share/icons/Newaita/actions/48/meld-version-control.svg
````

### (3b) Need new monochromatic icons for `meld-version-control.svg`

We are missing the  **_smaller_ `meld-version-control.svg` _monochromatic symbolic_** icons in Newaita. Because these are small icons, the new icons must be must be _monochromatic symbolic_ style.
```
/usr/share/icons/Newaita/actions/16/meld-version-control.svg
/usr/share/icons/Newaita/actions/22/meld-version-control.svg
/usr/share/icons/Newaita/actions/24/meld-version-control.svg
/usr/share/icons/Newaita/actions/32/meld-version-control.svg
```

---

### Additional information for the "File comparison" button icon

The "File comparison" button in Meld requires a 48x48 icon for `document-new.png`. Unfortunately, Newaita only has monochromatic symbolic versions of this icon that are 16, 22, 24, and 32 pixels. Therefore, Meld is forced to render a smaller monochromatic icon for this button.

![File comparison](https://user-images.githubusercontent.com/19394936/65294395-733e0880-db2c-11e9-95b8-eeed81e76b0c.png)

Here are the smaller monochromatic icons currently available in Newaita.
```
/usr/share/icons/Newaita/actions/16/document-new.svg
/usr/share/icons/Newaita/actions/22/document-new.svg
/usr/share/icons/Newaita/actions/24/document-new.svg
/usr/share/icons/Newaita/actions/32/document-new.svg
```
However, the solution isn't to simply create a larger (48 px) version of the existing `document-new.svg`, because the "style" of the icon should _not_ be monochromatic. Instead, at this size, the icon should be _colored_, like the folder icon used for the "Directory comparison" button (2).

![Directory comparison](https://user-images.githubusercontent.com/19394936/65294281-26f2c880-db2c-11e9-98dc-14a4b5c76346.png)

Note that a smaller `document-new.svg` is also used in Meld's toolbar. In the toolbar, the monochromatic symbolic icon looks appropriate.

![Meld toolbar](https://user-images.githubusercontent.com/19394936/65294720-0d9e4c00-db2d-11e9-88b3-8d101ac348c3.png)
 
### Additional information for the "Version control view" button icon

The "Version control view" button in Meld requires a 48x48 icon for `meld-version-control.png`. Newaita is missing this icon, so the application defaults to the 48x48 icon from the hicolor theme:

![Version control view](https://user-images.githubusercontent.com/19394936/65295714-3aa02e00-db30-11e9-9683-6f65c86c0424.png)

```
/usr/share/icons/hicolor/48x48/apps/meld-version-control.png
```

For icon sizes 16, 22, 24, and 32 pixels, it would be OK to add monochromatic symbolic versions of `meld-version-control.svg`. But for the 48 pixel version, the icon should be _colored_, like the folder icon used for the "Directory comparison" button (2).

![Directory comparison](https://user-images.githubusercontent.com/19394936/65294281-26f2c880-db2c-11e9-98dc-14a4b5c76346.png)

---

### Screenshot of Meld using Newaita icon theme

This image shows Meld incorrectly displaying a _small_ monochromatic icon for the "File comparison" button icon (A) using the Newaita icon theme. This image also shows Meld incorrectly displaying a large colored icon from the hicolor theme, for the "Version control view" button icon (3). The Newaita icon theme should supply the correct icons for both of these buttons.

![Screenshot from 2019-09-19 21-05-08](https://user-images.githubusercontent.com/19394936/65296680-2d387300-db33-11e9-8772-ffe61c7402e7.png)

### Screenshot of Meld using Gnome icon theme

This image shows Meld displaying a large colored icon for the "File comparison" button icon (A) using the Gnome icon theme. This image also shows Meld displaying a large colored icon from the hicolor theme, for the "Version control view" button icon (3).

![Screenshot from 2019-09-19 21-39-32](https://user-images.githubusercontent.com/19394936/65296759-83a5b180-db33-11e9-81c2-1ac10b2f8957.png)

**Comment by cbrnix** [comment]
I can try putting 48 size icons in Apps so as not to destroy the system. True, I'm not sure that the software will not pick them up as default ones for use.

**Comment by cbrnix** [comment]
Added. It seems that it did not affect the rest of the icons

**Comment by PJSingh5000** [comment]
Cbrnix,

Thanks.
This is an unusual situation, indeed, with the Meld application using 48 pixel icons as "action" icons.
I will try this out an comment back.

**Comment by PJSingh5000** [comment]
Looks good! Thanks!

![Screenshot from 2019-09-20 22-07-25](https://user-images.githubusercontent.com/19394936/65366546-6d5f2a80-dbf3-11e9-95fc-4077dd738728.png)
