### ISSUE TITLE
Transparent background broken on some mimes

### ISSUE THREAD

**Issue by demoy** [cbrnix/Newaita#129]
![Screenshot_20190923_024535](https://user-images.githubusercontent.com/2396524/65409096-79dab300-ddac-11e9-9a60-361d6eb87563.png)
The mimes I noticed having this concern [svg, sh, html, docx]. Hopefully this issue is reproducible on your end. I pulled today and still had the issue. I am not sure which commit it started because I pull infrequently.

**Comment by cbrnix** [comment]
Specify what size of the icons you use and what theme (Dark or normal). Because I check the files and find no transparency issues.
You can go to Code, click on Find file and paste
application-msword.svg
text-xml.svg
text-x-script.svg
libreoffice-drawing.svg

Transparent background in place, as far as I see

**Comment by demoy** [comment]
Thanks for the response. The screenshot is from icon theme for dark, at 32px. I tried the other icon theme and resize the icons. Appears black regardless.

I repeated your steps to find the icons and they are transparent in the firefox, also the only gnome application I installed (using KDE) shows them normally. Since you can't reproduce I will just close.

**Comment by cbrnix** [comment]
> Thanks for the response. The screenshot is from icon theme for dark, at 32px. I tried the other icon theme and resize the icons. Appears black regardless.
> 
> I repeated your steps to find the icons and they are transparent in the firefox, also the only gnome application I installed (using KDE) shows them normally. Since you can't reproduce I will just close.

Perhaps this is a render bug?

**Comment by cbrnix** [comment]
You know, I installed KDE and really discovered the problem. Now the backgrounds of the icons should be fixed. Not sure about apps

**Comment by cbrnix** [comment]
> Thanks for the response. The screenshot is from icon theme for dark, at 32px. I tried the other icon theme and resize the icons. Appears black regardless.
> 
> I repeated your steps to find the icons and they are transparent in the firefox, also the only gnome application I installed (using KDE) shows them normally. Since you can't reproduce I will just close.

You know, I installed KDE and really discovered the problem. Now the backgrounds of the icons should be fixed. Not sure about apps

**Comment by demoy** [comment]
Thank you for going through so much trouble. I am guessing your fix is still on your local branch because I see the latest commit only touches apps. I only have the stock Kubuntu applications installed and a few additions, so my sample size is small but I don't see any background issues with app icons.

**Comment by cbrnix** [comment]
> Thank you for going through so much trouble. ~I am guessing your fix is still on your local branch because I see the latest commit only touches apps.~ I only have the stock Kubuntu applications installed and a few additions, so my sample size is small but I don't see any background issues with app icons.
> 
> EDIT: thanks I see the fix, I pull the wrong theme initially. You can close when you want to.

In the next couple of days I will look at other categories for these errors. Honestly, I'm surprised that only KDE displays them
