### ISSUE TITLE
Arrow icon on Downloads

### ISSUE THREAD

**Issue by raulcraveiro** [cbrnix/Newaita#137]
I don't know if It is supposed to be this way, or if I have a bug, but the downloads folder icon is a "regular" folder. This gets me confused everytime that I try to found the downloads folder and It isn't a arrow icon.

![image](https://user-images.githubusercontent.com/5623492/69843538-b7ddd280-1246-11ea-8a39-74f0d1797716.png)

@Edit

I just realized that happens after i use the "fv.sh" script to change my folders to blue.

**Comment by cbrnix** [comment]
What is DE? Are you sure this folder is assigned the value 'Downloads'?

**Comment by raulcraveiro** [comment]
I'm on Pop!_OS 19.10, using Gnome DE. Yes, It has the "Downloads" value.

I was checking yesterday, before I use the script, It's okay, because he uses the Adwaita folders and icons on the sidebar, but when I use the script and It creates the .places folder, the folders are ok, but the sidebar gets all messed up.

![image](https://user-images.githubusercontent.com/5623492/69968251-c6531500-14f8-11ea-858c-10b2214a7a59.png)

**Comment by raulcraveiro** [comment]
When I install the Newaita, it uses the Adwaita folder. I don't know if It's something different on Pop!_OS, but I don't know what to do :thinking: 

![image](https://user-images.githubusercontent.com/5623492/70464066-ed7f8880-1a9c-11ea-9347-cca425119d38.png)

**Comment by raulcraveiro** [comment]
With the last update on Newaita, now It works correctly. Thank you!
