### ISSUE TITLE
Icon request: Hyper Terminal

### ISSUE THREAD

**Issue by benclark06** [cbrnix/Newaita#14]
An icon for hyperterm would be much appreciated 
# Icon:
![image](https://user-images.githubusercontent.com/33701263/45452968-567c2300-b6d7-11e8-8f9d-f47697d3c670.png)

**Comment by cbrnix** [comment]
does linux have a hyperterminal? Can I link to a developer?

**Comment by benclark06** [comment]
Yes, it's available for linux, https://github.com/zeit/hyper

**Comment by cbrnix** [comment]
I added a hyperterm icon, but did not know the specification. It turns out hyper has a bad Hyper.desktop. You can change the line in it
Icon = / usr / share / pixmaps / hyper.png
to get it
icon = hyperterm

**Comment by benclark06** [comment]
Great, thanks!
