### ISSUE TITLE
icon request: KDE added "Recent Locations" to file manager

### ISSUE THREAD

**Issue by demoy** [cbrnix/Newaita#140]
![Screenshot_20200112_092004](https://user-images.githubusercontent.com/2396524/72220352-d27db980-351d-11ea-9448-33546e4dad47.png)
Recent files also seems blurry because of the badge. I know the default Breeze icon iteration is going down the road of putting tiny badges on already tiny icons. But if possible can you design something that has less legibility issues than tiny badges on tiny icons. Take as much time as you need to think something, I don't mind waiting. I will also post back here if I have any ideas my self.

Unrelated but great job on the color inheriting icons. Your icon theme look like something I should have to pay a large amnt of money to use.

**Comment by demoy** [comment]
The Flatery icon theme instead of trying to fit a clock into the badge space uses what I commonly see as an undo icon [I believe it means redo in this context] on the folder and document icon to mean recent. It's visually legible since the stems can be thicker than a clock and there are no small notches needed.
![Screenshot_20200120_070057](https://user-images.githubusercontent.com/2396524/72725335-7cc79380-3b53-11ea-8913-518758b1bd1a.png)

**Comment by cbrnix** [comment]
Added

**Comment by demoy** [comment]
Thank you. I noticed that the "recent document badge" is more blurry than the "recent folder badge". 
![Screenshot_20200315_092858](https://user-images.githubusercontent.com/2396524/76703645-f76ae600-66a0-11ea-9a4e-399848cd52ca.png)

Because they are beside each other it's hard to unotice. Could you change one to be the same as the other? 

Side note: the red dot on the calender for yesterday is great!

**Comment by cbrnix** [comment]
Everything is much more complicated here. As soon as I find enough time, I will change all the 'action' icons. So far this is a temporary measure.
Icons of size 16 have a blur problem. It is difficult to eliminate without checking each icon.

**Comment by cbrnix** [comment]
![Screenshot_20200315_195517](https://user-images.githubusercontent.com/40643537/76706235-054b5600-66f7-11ea-9502-bf9acae1d632.png)

**Comment by demoy** [comment]
Oh great. I always thought the slight blurriness of the action icons was a design choice. The changes are nice, I like the current designs too. I do find the changes easier to "read" visually.

![Screenshot_20200315_124801](https://user-images.githubusercontent.com/2396524/76707330-3d817300-66bc-11ea-991e-2c0cfb32348f.png)

:)

**Comment by cbrnix** [comment]
Most likely, I will do it in stages. First 16, then 22, etc.
