### ISSUE TITLE
Wrong battery icon in Gnome

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#143]
The battery icon isn't showing correctly in Gnome 3.36.

![Captura de tela de 2020-03-27 11-37-30](https://user-images.githubusercontent.com/11943860/77767365-b6b78900-701f-11ea-8e94-4242988ecd1c.png)

**Comment by cbrnix** [comment]
The coming days I will completely replace the panel icons. Bear with a little. Almost done

**Comment by cbrnix** [comment]
Check pls.

**Comment by btd1337** [comment]
The error persists. I think the new icon is missing.

![Captura de tela de 2020-03-30 09-01-35](https://user-images.githubusercontent.com/11943860/77910259-3d10dc80-7265-11ea-8acc-5e50952a0249.png)

**Comment by cbrnix** [comment]
I added battery level icons. Now, in theory, it should be fine

**Comment by btd1337** [comment]
The error persists, icon still missing :/

**Comment by cbrnix** [comment]
battery-full-charged-symbolic  i think. Added this

**Comment by btd1337** [comment]
Now.

![Captura de tela de 2020-03-31 05-04-30](https://user-images.githubusercontent.com/11943860/78002229-43f32a00-730d-11ea-9036-552081f77ed6.png)

![Captura de tela de 2020-03-31 05-04-10](https://user-images.githubusercontent.com/11943860/78002232-448bc080-730d-11ea-9b10-4493f0b20ecd.png)

I'll leave the notebook without charger to see if all the icons are OK.

**Comment by btd1337** [comment]
It tested! All it's OK. Thanks again!
