### ISSUE TITLE
Partial Installation

### ISSUE THREAD

**Issue by 73** [cbrnix/Newaita#144]
Hi. I think Newaita is gorgeous. Thank you for your hard work. I use Newaita on all my computers that run GNOME and keep up with `master`. However, recently new icons appeared for *actions*, *emblems*, and *places*.

They appear way too thin for my taste and in combination with Thunderbird Icons etc. 
Is it possible to install only the rest of Newaita? And if so, what would be the preferred workflow?

**Comment by cbrnix** [comment]
At the moment, icons for gnome have links to the same (not symbolic) ones. Later I will make separate icons. So far this is a temporary measure. Unfortunately, the developers of different DE have their own approaches.

**Comment by cbrnix** [comment]
You can go to the Newaita directory, find through the search all the 'symbolic' icons and delete them. The theme will use Adwaita icons for this

**Comment by 73** [comment]
Thank you for getting back to me that quickly.
I am not sure I understand. I tried: 
```
rm -rf actions/symbolic/*
rm -rf places/symbolic/*
rm -rf emblems/symbolic/*
```
which yielded:
![image](https://user-images.githubusercontent.com/529346/78015631-f2b55b80-7349-11ea-8122-13b5d66e492a.png)

But I guess that is not what you had in mind.

**Comment by cbrnix** [comment]
I meant that you need to delete all files containing the name "-symbolic"

**Comment by 73** [comment]
Okay. I tried deleting all this files using `find . -name "*-symbolic*" -delete` yielded the same result.

**Comment by cbrnix** [comment]
gtk-update-icon-cache ./
in directory

**Comment by cbrnix** [comment]
Oh. 
Inherits=Adwaita index file

**Comment by 73** [comment]
Perfect! Thanks a lot. 
```
Inherits=Adwaita
```
in the index.theme does not seem needed.
