### ISSUE TITLE
The 16px and 22px "places" icons do not have "dark" variants.

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#149]
__SUMMARY__

The 16px and 22px _places_ icons use the same images for both the "light" and "dark" variants.

(This is only an issue for the smaller 16px and 22px size icons, because they are monochrome, whereas the larger icons using color images do not exhibit this issue).

As an example of how it should be, see the 16px and 22px _actions_ icons which have both a "light" variant and a "dark" variant.

__DETAILS__

PROBLEM

(1)
`/usr/share/icons/Newaita-dark/.places-*/16/`
...uses the same Light variant icons as....
`/usr/share/icons/Newaita/.places-*/16/`

(2)
`/usr/share/icons/Newaita-dark/.places-*/22/`
...uses the same Light variant icons as....
`/usr/share/icons/Newaita/.places-*/22/`

SPECIFIC EXAMPLE

This applies to all the 16px and 22 px _places_ icons, but here is one specific example...

- `/usr/share/icons/Newaita/.places-default/22/gtk-directory.svg` is a link to `/usr/share/icons/Newaita/.places-default/22/folder.svg`

- `/usr/share/icons/Newaita-dark/.places-default/22/gtk-directory.svg` is a link to `/usr/share/icons/Newaita-dark/.places-default/22/folder.svg`

- However, both `.../Newaita/.places-default/22/folder.svg` and `.../Newaita-dark/.places-default/22/folder.svg` contain light icons.

EXAMPLE OF HOW IT SHOULD WORK

In contrast, the Newaita _actions_ icons correctly have both light and dark variants...

(3)
`/usr/share/icons/Newaita-dark/.actions-*/16/`
...uses DIFFERENT icons from...
`/usr/share/icons/Newaita/.actions-*/16/`

(4)
`/usr/share/icons/Newaita-dark/.actions-*/22/`
...uses DIFFERENT icons from...
`/usr/share/icons/Newaita/.actions-*/22/`

__SCREENSHOTS OF THE ISSUE__

![Newaita_with_Light_Theme](https://user-images.githubusercontent.com/19394936/80317395-92db9480-87d1-11ea-9b9a-96eeb0ba7489.png)

![Newaita-dark_with_Dark_Theme png](https://user-images.githubusercontent.com/19394936/80317400-9838df00-87d1-11ea-916b-0a2b8a691a12.png)

__RECREATE THE ISSUE__

Save the following file as `places_icons_example.glade`.

Open this file in the Glade application. Then highlight "GtkWindow" in the left pane, and click the "Preview snapshot" icon at the bottom of the left pane.

1. Change your Gtk theme to a light theme (such as Yaru or Adwaita). Change your icon theme to Newaita. Everything looks OK.

2. Change your Gtk theme to a dark theme (such as Yaru-dark). Notice the icons are barely visible, since they are still using the (light) Newaita icon theme. This is expected.

3. Next, change your Icon theme to Newaita-dark. Notice the _action_ icon (gtk-open) is correctly showing a dark variant and is visible against the dark background. Notice the _places_ icon (gtk-directory) is STILL  showing the LIGHT variant ad is NOT visible against the dark background. The expected behavior is for gtk-directory to be rendered using a different appropriate image for folder.svg.

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.1 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <object class="GtkWindow">
    <property name="can_focus">False</property>
    <property name="border_width">18</property>
    <child>
      <placeholder/>
    </child>
    <child>
      <object class="GtkGrid">
        <property name="width_request">400</property>
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="row_spacing">16</property>
        <property name="column_spacing">16</property>
        <property name="row_homogeneous">True</property>
        <child>
          <object class="GtkImage">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="stock">gtk-open</property>
          </object>
          <packing>
            <property name="left_attach">0</property>
            <property name="top_attach">0</property>
          </packing>
        </child>
        <child>
          <object class="GtkLabel">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="hexpand">True</property>
            <property name="label" translatable="yes">This action icon (gtk-open) has both a light and dark variant, so it can be changed with the theme. (Try changing your Icon theme, alternating between Newaita and Newaita-dark, and see how the icon changes).</property>
            <property name="wrap">True</property>
            <property name="max_width_chars">0</property>
            <property name="xalign">0</property>
          </object>
          <packing>
            <property name="left_attach">1</property>
            <property name="top_attach">0</property>
          </packing>
        </child>
        <child>
          <object class="GtkImage">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="stock">gtk-directory</property>
          </object>
          <packing>
            <property name="left_attach">0</property>
            <property name="top_attach">1</property>
          </packing>
        </child>
        <child>
          <object class="GtkLabel">
            <property name="visible">True</property>
            <property name="can_focus">False</property>
            <property name="hexpand">True</property>
            <property name="label" translatable="yes">This places icon (gtk-directory) only has a light variant. When the theme is changed, this icon stays the same. This is a problem when a dark GTK theme is selected along with the Newaita-dark icon theme. (Try changing your Icon them, alternating between Newaita and Newaita-dark, and see how the icon stays the same).</property>
            <property name="wrap">True</property>
            <property name="max_width_chars">0</property>
            <property name="xalign">0</property>
          </object>
          <packing>
            <property name="left_attach">1</property>
            <property name="top_attach">1</property>
          </packing>
        </child>
      </object>
    </child>
  </object>
</interface>
```

**Comment by cbrnix** [comment]
Let's start with which version you are using. In git, dark and light themes use the corresponding monochrome icons. Moreover, they have a parameter:
<defs>
   <style id = "current-color-scheme" type = "text / css">
    .ColorScheme-Text {color: #eeeeee; } .ColorScheme-Highlight {color: # 424242; }
   </style>
  </defs>
Allowing CSS level to change color independently, depending on the background

**Comment by cbrnix** [comment]
https://github.com/cbrnix/Newaita/blob/master/Newaita-dark/.places-aqua/16/folder.svg

https://github.com/cbrnix/Newaita/blob/master/Newaita/.places-aqua/16/folder.svg

Here is an example of monochrome icons in dark and light themes

**Comment by cbrnix** [comment]
After changing the theme from dark to light, you tried
gtk-update-icon-cache?

**Comment by cbrnix** [comment]
If you use the AUR version, then I do not do it. It may be outdated at this time.

**Comment by PJSingh5000** [comment]
Thanks for looking @ this.
I'll reinstall and check.

**Comment by PJSingh5000** [comment]
I downloaded and tested the latest release, and the issue I had reported is no longer present.

Thanks for your time once again.
This is truly a beautiful and comprehensive icon theme.
You responsiveness and talent are unmatched!!

![Screenshot from 2020-05-08 10-30-13](https://user-images.githubusercontent.com/19394936/81416233-6c91ef00-9117-11ea-80d5-c01eec5f7e86.png)
