### ISSUE TITLE
Crow Translate tray icon

### ISSUE THREAD

**Issue by Shatur95** [cbrnix/Newaita#155]
You already have tray icons for light and dark variants (`crow-translate-tray-dark.svg` and `crow-translate-tray-light.svg`), but missing `crow-translate-tray.svg` that contains light or dark depends on theme variant. I also suggest to move such icon to `panel` as in [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/16x16/panel/crow-translate-tray.svg) theme.

I laso noticed that dark and light variants looks the same in theme variant (all dark or all light). They thought to be different.

**Comment by cbrnix** [comment]
Added

**Comment by Shatur95** [comment]
Thanks! But `crow-translate-dark.svg` and `crow-translate-light.svg` still looks the same (both are light in light theme variant and both are dark in dark variant). Could you make this icons independent of theme? I mean to always use light variant for `crow-translate-dark.svg` and always use dark for `crow-translate-light.svg`?

[Here](https://github.com/crow-translate/crow-translate/tree/master/dist/unix/generic/hicolor) is how the icons look originally.

**Comment by cbrnix** [comment]
In gtk3, they must independently change the color. Later, if you want, I will do

**Comment by Shatur95** [comment]
In this app only `crow-translate-tray.svg` changes color depends on theme. `crow-translate-dark.svg` and `crow-translated-dark.svg` needed if user want to set icon style independently. The same approach you can see in qBittorrent.

**Comment by cbrnix** [comment]
check, pls

**Comment by Shatur95** [comment]
Thanks you a lot, now as expected :)
