### ISSUE TITLE
Intel, Nvidia and hybrid icons

### ISSUE THREAD

**Issue by Shatur95** [cbrnix/Newaita#156]
Such icons used by Ubuntu Prime and Optimus Manager (need to show current videocard in notebooks). Could you add it?
[Here](https://github.com/Shatur95/optimus-manager-qt/tree/master/dist/icons) is the folder with proper names that contains default variants.

**Comment by cbrnix** [comment]
Added

**Comment by Shatur95** [comment]
Thanks! But I I would expect if the hybrid icon will be monochrome too. Maybe it would be better to mate it monochrome but with different pic?

**Comment by cbrnix** [comment]
Dit it

**Comment by Shatur95** [comment]
Thank you, very nice icon!
