### ISSUE TITLE
DoomEmacsicon

### ISSUE THREAD

**Issue by ALipAkrohk** [cbrnix/Newaita#157]
App Name : [Gnu Emacs ](https://www.gnu.org/software/emacs/)
Fork Name : [Doom Emacs](https://gitlab.com/hlissner/doom-emacs)
icon Name : DoomEmacs
Wiki & Documents : [Page ](https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org) 
icon : ![icon](https://assets.gitlab-static.net/uploads/-/system/project/avatar/1224119/Emacs-icon.png)

**Comment by cbrnix** [comment]
Link added

**Comment by ALipAkrohk** [comment]
> Link added
I don't understand what you mean!

**Comment by cbrnix** [comment]
> > Link added
> 
> I don't understand what you mean!

Added link to emacs
