### ISSUE TITLE
No Release

### ISSUE THREAD

**Issue by TeenCorn** [cbrnix/Newaita#161]
I'm trying to package these icons for Solus. Currently it is [blocked](https://dev.getsol.us/T9061) from being included because there is no release.

Is there a reason not to mark a release?

**Comment by cbrnix** [comment]
Noted the release. But is it worth it?

**Comment by TeenCorn** [comment]
Yes it's worth since I don't have go to github or gnome-look to download the icon theme every time I want to use it on other computers running Solus
