### ISSUE TITLE
[Icon Request] Toolbox App ,Goland, .go

### ISSUE THREAD

**Issue by Yakumo-Yukari** [cbrnix/Newaita#166]
![ToolboxApp](https://user-images.githubusercontent.com/12076232/87292816-f5704100-c533-11ea-8d14-52ef002f45ac.png)

- [x] Toolbox App

![goland](https://user-images.githubusercontent.com/12076232/87292858-06b94d80-c534-11ea-9f3d-af3395644dbf.png)

- [x] Goland

![qq](https://user-images.githubusercontent.com/12076232/87293577-19805200-c535-11ea-9ed5-535c1ed4a5e4.png)

- [x] QQ

![go](https://user-images.githubusercontent.com/12076232/87292935-23ee1c00-c534-11ea-87b3-dee74b3153e6.png)

- [x] .go  golang code file

**Comment by cbrnix** [comment]
goland, jetbrains-toolbox and text-x-go icons has been around for a long time

**Comment by cbrnix** [comment]
Added. But their use requires changing the desktop files (or forced change in the menu)
