### ISSUE TITLE
Huge volume icon in GNOME-MPV and videos?

### ISSUE THREAD

**Issue by GorrillaRibs** [cbrnix/Newaita#17]
![screenshot from 2018-10-01 00-40-30](https://user-images.githubusercontent.com/16048044/46269977-aef25380-c512-11e8-95ac-5ed3b0f8a9a1.png)

Not sure what's going on here, but figured I'd report it. Using Newaita Dark. Thanks in advance!

**Comment by cbrnix** [comment]
Are you using the latest update from github?

**Comment by GorrillaRibs** [comment]
Using the latest, yep! Just found out about these icons yesterday. Removing the 'scalable' dir from 'panel' in Newaita-Dark does indeed fix it!

**Comment by cbrnix** [comment]
In the near future I am going to limit the size of the icons and make them fixed to avoid such problems. The structure will have to change
