### ISSUE TITLE
Fix Wrong Apps

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#21]
Planner is currently pointing to the Gnome Pomodoro icon.
And the Gnome Pomodoro is pointing to the wrong alarm clock icon.

1. **Planner**
- Comment=project and task management tool
- Icon=com.github.alainm23.planner
- Note: [Icon Link](https://steemitimages.com/DQmUHicihmPz2m8pfewd2LEMs2aoLLB2SWr5G3BBdsn48dx/1.png)

2. **Gnome Pomodoro**
- Comment=A simple time management utility
- Icon=gnome-pomodoro
- Note: [Icon Link](http://gnomepomodoro.org/images/icons/256x256.png)

**Comment by btd1337** [comment]
Gnome Pomodoro link is fixed in this PR https://github.com/cbrnix/Newaita/pull/22/commits/105babb8f783835d0cfa0c228cae15978e95bc15

**Comment by cbrnix** [comment]
Fixed

**Comment by btd1337** [comment]
Tested!
