### ISSUE TITLE
Paypal donate button

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#25]
Consider to add a Paypal donate button to your repository:

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/#

Example: In the bottom of [this repository](https://github.com/btd1337/elementary-script)

**Comment by cbrnix** [comment]
I have not found Tools in the Russian version of XD

**Comment by btd1337** [comment]
Stay well hidden! I also took time to find the Brazilian version!

**Comment by cbrnix** [comment]
And how to write the code in the readme?

**Comment by cbrnix** [comment]
Created a button, but it is in html. I understand that i need bb?

**Comment by btd1337** [comment]
@cbrnix I updated the package description on AUR. Now this included in description the paypal donate link: https://aur.archlinux.org/packages/newaita-icons-git/

**Comment by cbrnix** [comment]
Thanks for you help:)
