### ISSUE TITLE
theme Newaita has no size field

### ISSUE THREAD

**Issue by 0pLuS0** [cbrnix/Newaita#3]
Hi,

I just noticed in my logs all these messages;

(lxappearance:1680): Gtk-WARNING **: Theme directory mimetypes/32 of theme Newaita has no size field

(lxappearance:1680): Gtk-WARNING **: Theme directory  of theme Newaita has no size field

(lxappearance:1680): Gtk-WARNING **: Theme directory apps/64 of theme Newaita has no size field

(lxappearance:1680): Gtk-WARNING **: Theme directory apps/128 of theme Newaita has no size field

(lxappearance:1680): Gtk-WARNING **: Theme directory apps/256 of theme Newaita has no size field

(lxappearance:1680): Gtk-WARNING **: Theme directory categories/scalable of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory mimetypes/32 of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory  of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory apps/64 of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory apps/128 of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory apps/256 of theme Newaita has no size field

(firefox:1483): Gtk-WARNING **: Theme directory categories/scalable of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory mimetypes/32 of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory  of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory apps/64 of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory apps/128 of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory apps/256 of theme Newaita has no size field

(spacefm:1681): Gtk-WARNING **: Theme directory categories/scalable of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory mimetypes/32 of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory  of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory apps/64 of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory apps/128 of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory apps/256 of theme Newaita has no size field

(lxappearance:1696): Gtk-WARNING **: Theme directory categories/scalable of theme Newaita has no size field

**Comment by cbrnix** [comment]
This from aur version?

**Comment by 0pLuS0** [comment]
I'm just getting off of GitHub here, and when you were making changes I was doing git pull. So I deleted everything, and ran git clone, so with a fresh start, I still see all these messages.

**Comment by cbrnix** [comment]
Try now please, i correct index file. 
If the problem persists, I will understand when I have a weekend

**Comment by 0pLuS0** [comment]
It looks like you're getting it, still one to go I believe.

I ran through a lot of my apps... 

(lxappearance:2875): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(firefox:2581): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(spacefm:2876): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(transmission-gtk:2893): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(gimp:3067): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(viewnior:3080): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(hexchat:3097): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(gmtp:3100): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(pavucontrol:3126): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

/usr/share/bleachbit/GUI.py:875: GtkWarning: Theme directory devices/32 of theme Newaita has no size field

(nvidia-settings:3129): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(xfce4-notifyd-config:3130): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(obconf:3131): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

**Comment by 0pLuS0** [comment]
It looks like you're getting it, still one to go I believe. Seems to be only ```devices/32``` left...

I ran through a lot of my apps... 

(lxappearance:2875): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(firefox:2581): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(spacefm:2876): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(transmission-gtk:2893): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(gimp:3067): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(viewnior:3080): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(hexchat:3097): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(gmtp:3100): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(pavucontrol:3126): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

/usr/share/bleachbit/GUI.py:875: GtkWarning: Theme directory devices/32 of theme Newaita has no size field

(nvidia-settings:3129): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(xfce4-notifyd-config:3130): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

(obconf:3131): Gtk-WARNING **: Theme directory devices/32 of theme Newaita has no size field

**Comment by 0pLuS0** [comment]
I'm not seeing this anymore...

Btw, the iconset is really coming along nice, I like the new changes I see with menu icons, the little splashs of color, quite the Picasso :)

**Comment by cbrnix** [comment]
Thanks for you help!:) Stand by me:D
