### ISSUE TITLE
Request Missing icons

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#30]
- [x] 1. **Comgen**
- Comment=Generate styled comments for your code
- Icon=com.github.jeremyvaartjes.comgen
- Note: [Icon Link](https://github.com/jeremyvaartjes/comgen/blob/master/data/icons/128/com.github.jeremyvaartjes.comgen.svg)

- [x] 2. **Handbrake**
- Comment=Multimedia Converter
- Icon=fr.handbrake.ghb
- Note: [Icon Link](http://erichansen.tv/wp-content/uploads/2013/01/HandBrake-icon.jpg)

- [x] 3. **Gamehub**
- Comment=All your games in one place
- Icon=com.github.tkashkin.gamehub
- Note: [Icon Link](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTH7kxSUyL8YuX0SLzEkIGl_jkrt6XOmXYSW_qjpBjlh1h2ghrs)

- [x] 4. **Ping**
- Comment=Test your API against some data
- Icon=com.github.jeremyvaartjes.ping
- Note: [Icon Link](https://github.com/jeremyvaartjes/ping/blob/master/data/icons/128/com.github.jeremyvaartjes.ping.svg)

- [x] 5. **Timetable**
- Comment=Plot out your own timetable for the week and organize it
- Icon=com.github.lainsce.timetable
- Note: [Icon Link](https://github.com/lainsce/timetable/blob/master/data/icons/128/com.github.lainsce.timetable.svg)

- [x] 6. **Agenda**
- Comment=A simple, fast, no-nonsense to-do (task) list.
- Icon=com.github.dahenson.agenda
- Note: [Icon Link](https://github.com/dahenson/agenda/blob/master/data/icons/128/com.github.dahenson.agenda.svg)

- [x] 7. **AppEditor**
- Comment=Edit application menu
- Icon=com.github.donadigo.appeditor
- Note: [Icon Link](https://github.com/donadigo/appeditor/blob/master/data/icons/128/com.github.donadigo.appeditor.svg)

- [x] 8. **Bookworm**
- Comment=A focused eBook reader
- Icon=com.github.babluboy.bookworm
- Note: [Icon Link](https://github.com/babluboy/bookworm/blob/master/data/icons/128/com.github.babluboy.bookworm.svg)

- [x] 9. **Clipped**
- Comment=Manage your clipboard with ease
- Icon=com.github.davidmhewitt.clipped
- Note: [Icon Link](https://github.com/davidmhewitt/clipped/blob/master/data/128/com.github.davidmhewitt.clipped.svg)

- [x] 10. **Cozy**
- Comment=A modern audio book player
- Icon=com.github.geigi.cozy
- Note: [Icon Link](https://github.com/geigi/cozy/blob/master/data/icons/hicolor/128x128/apps/com.github.geigi.cozy.svg)

- [x] 11. **Develop**
- Comment=Creates elementary OS apps and widgets
- Icon=com.github.alcadica.develop
- Note: [Icon Link](https://github.com/alcadica/develop/tree/master/data/icons/com.github.alcadica.develop.svg)

- [x] 12. **Fondo**
- Comment=Find the most beautiful wallpapers
- Icon=com.github.calo001.fondo
- Note: [Icon Link](https://github.com/calo001/fondo/blob/master/data/images/icons/128/com.github.calo001.fondo.svg)

- [x] 13. **Gnonograms**
- Comment=Create and solve gnonogram puzzles
- Icon=com.github.jeremypw.gnonograms
- Note: [Icon Link](https://github.com/jeremypw/gnonograms/blob/master/data/icons/128/com.github.jeremypw.gnonograms.svg)

- [x] 14. **Hackup**
- Comment=Read Hacker News from the desktop
- Icon=com.github.mdh34.hackup
- Note: [Icon Link](https://github.com/jeremypw/gnonograms/blob/master/data/icons/128/com.github.mdh34.hackup.svg)

- [x] 15. **Hashit**
- Comment=Create and solve gnonogram puzzles
- Icon=com.github.artemanufrij.hashit
- Note: [Icon Link](https://github.com/artemanufrij/hashit/blob/master/data/icons/64/com.github.artemanufrij.hashit.svg)

- [x] 16. **Iconoscope**
- Comment=Simple icon visualizer
- Icon=com.github.santileortiz.iconoscope
- Note: [Icon Link](https://github.com/santileortiz/Iconoscope/blob/master/data/128/iconoscope.svg)

- [x] 17. **Locksmith**
- Comment=Generate strong, secure passwords
- Icon=com.github.christophernugent.locksmith
- Note: [Icon Link](https://github.com/ChristopherNugent/Locksmith/blob/master/data/images/icons/128/com.github.christophernugent.locksmith.svg)

- [x] 18. **Spice-Up**
- Comment=Create simple and beautiful presentations
- Icon=com.github.philip-scott.spice-up
- Note: [Icon Link](https://github.com/aljelly/Spice-up/blob/new-icons/data/icons/64/com.github.philip-scott.spice-up.svg)

- [x] 19. **Taxi**
- Comment=The FTP Client that drives you anywhere
- Icon=com.github.alecaddd.taxi
- Note: [Icon Link](https://github.com/Alecaddd/taxi/blob/master/data/icons/128.svg)

- [x] 20. **Regex Tester**
- Comment=A simple app for testing regular expressions
- Icon=com.github.artemanufrij.regextester
- Note: [Icon Link](https://github.com/artemanufrij/regextester/blob/master/data/icons/64/com.github.artemanufrij.regextester.svg)

- [x] 21. **ValaCompiler**
- Comment=Create and solve gnonogram puzzles
- Icon=com.github.basjam.valacompiler
- Note: [Icon Link](https://github.com/basjam/ValaCompiler/blob/master/data/icons/128/com.github.basjam.valacompiler.svg)

- [x] 22. **Palaura**
- Comment=Dictionary
- Icon=com.github.lainsce.palaura
- Note: [Icon Link](https://github.com/lainsce/palaura/blob/master/data/icons/128/com.github.lainsce.palaura.svg)

- [x] 23. **Ideogram**
- Comment=Insert emoji anywhere
- Icon=com.github.cassidyjames.ideogram
- Note: [Icon Link](https://github.com/cassidyjames/ideogram/blob/master/data/icons/128.svg)

- [x] 24. **Nutty**
- Comment=A advanced network utility
- Icon=com.github.babluboy.nutty
- Note: [Icon Link](https://github.com/babluboy/nutty/blob/master/data/icons/128/com.github.babluboy.nutty.svg)

**Comment by cbrnix** [comment]
Done

**Comment by btd1337** [comment]
@cbrnix Your work is getting better every day!

**Comment by btd1337** [comment]
Let me just make a few comments:

1. Fix Iconoscope icon link
_From:_ iconoscope
_To:_ com.github.santileortiz.iconoscope

2. Timetable icon:
Timetable is a personal scheduler app. It received a to-do app icon.
I believe it could be replaced.

3. Comgen and Hashit
They seem to have some design error.

![captura de tela de 2018-11-12 20-55-18](https://user-images.githubusercontent.com/11943860/48380432-dd8d4d80-e6be-11e8-8fa5-f906305fc3ff.png)

![captura de tela de 2018-11-12 20-53-55](https://user-images.githubusercontent.com/11943860/48380440-e3832e80-e6be-11e8-8202-d0a9e846e5dc.png)

Out of these 3 observations, your work was of extreme quality!

**Comment by btd1337** [comment]
@cbrnix Only this one was missing.

- [x] 16. **Iconoscope**
- Comment=Simple icon visualizer
- Icon=com.github.santileortiz.iconoscope
- Note: [Icon Link](https://github.com/santileortiz/Iconoscope/blob/master/data/128/iconoscope.svg)

**Comment by cbrnix** [comment]
@btd1337
Did it.

**Comment by btd1337** [comment]
@cbrnix Your work is becoming the best!

Congratulations on your talent!

The [elementary collection](https://appcenter.elementary.io/) is almost all complete in its pack of icons!!! Amazing!

**Comment by cbrnix** [comment]
Thanks! It is good that there is not much left (though there is still enough work and beyond that)

**Comment by btd1337** [comment]
@cbrnix By the way, are you a designer in Russia?

**Comment by cbrnix** [comment]
I do not even have to do with the design :) Just a hobby

**Comment by btd1337** [comment]
Do you have professional designer's profile!

**Comment by cbrnix** [comment]
You flatter me XD
