### ISSUE TITLE
Request Appcenter Missing Icons

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#34]
Some more important AppCenter icons that are missing.

You're almost completing the collection ...

- [x] **Alias**
- Comment=A tool to manage your bash aliases
- Icon=com.github.bartzaalberg.alias
- Note: [Icon Link](https://github.com/bartzaalberg/alias/blob/master/data/icons/128/com.github.bartzaalberg.alias.svg)

- [x] **Bookmark Manager**
- Comment=Manage your SSH bookmarks
- Icon=com.github.bartzaalberg.bookmark-manager
- Note: [Icon Link](https://github.com/bartzaalberg/bookmark-manager/blob/master/data/icons/128/com.github.bartzaalberg.bookmark-manager.svg)

- [x] **Cinema**
- Comment=A video player for watching local video files
- Icon=com.github.artemanufrij.playmyvideos
- Note: [Icon Link](https://github.com/artemanufrij/playmyvideos/blob/master/data/icons/64/com.github.artemanufrij.playmyvideos.svg)

- [x] **Cipher**
- Comment=Encode and decode text
- Icon=com.github.arshubham.cipher
- Note: [Icon Link](https://github.com/arshubham/cipher/blob/master/data/images/icons/128/com.github.arshubham.cipher.svg)

- [x] **Copy Paste Grab**
- Comment=Download videos from hundreds of websites
- Icon=com.github.cryptowyrm.copypastegrab
- Note: [Icon Link](https://github.com/cryptowyrm/copypastegrab/blob/master/data/icons/128/com.github.cryptowyrm.copypastegrab.svg)

- [x] **Dimmer**
- Comment=Change screen's brightness
- Icon=com.github.panosx2.brightness
- Note: [Icon Link](https://github.com/panosx2/brightness/blob/master/icons/128/com.github.panosx2.brightness.png)

- [x] **Dino**
- Comment=Modern XMPP ("Jabber")
- Icon=im.dino.Dino
- Note: [Icon Link](https://github.com/dino/dino/blob/master/main/data/icons/im.dino.Dino.svg)

- [x] **EasySSH**
- Comment=SSH Connection Manager
- Icon=com.github.muriloventuroso.easyssh
- Note: [Icon Link](https://github.com/muriloventuroso/easyssh/blob/master/data/icons/128/com.github.muriloventuroso.easyssh.svg)

- [x] **Formatter**
- Comment=A simple device formatter
- Icon=com.github.djaler.formatter
- Note: [Icon Link](https://github.com/Djaler/Formatter/blob/master/data/icons/com.github.djaler.formatter.svg)

- [x] **Gifup**
- Comment=Create GIFs from Videos quickly
- Icon=com.github.bharatkalluri.gifup
- Note: [Icon Link](https://github.com/BharatKalluri/Gifup/blob/master/data/icons/128/com.github.bharatkalluri.gifup.svg)

- [x] **GraphUI**
- Comment=Graph Visualization
- Icon=com.github.artemanufrij.graphui
- Note: [Icon Link](https://github.com/artemanufrij/graphui/blob/master/data/icons/128/com.github.artemanufrij.graphui.svg)

- [x] **Mindi**
- Comment=A simple Audio converter
- Icon=com.github.torikulhabib.mindi
- Note: [Icon Link](https://github.com/torikulhabib/mindi/blob/master/data/icons/128.svg)

- [x] **MuseIC**
- Comment=Simple and fast music player with remote control
- Icon=com.github.bcedu.museic
- Note: [Icon Link](https://github.com/bcedu/MuseIC/blob/master/data/icons/com.github.bcedu.museic.svg)

- [x] **Palette**
- Comment=View and copy colors from the elementary brand palette
- Icon=com.github.cassidyjames.palette
- Note: [Icon Link](https://github.com/cassidyjames/palette/blob/master/data/icons/128.svg)

- [x] **PHP Tester**
- Comment=A simple tool to test your PHP code.
- Icon=com.github.bartzaalberg.php-tester
- Note: [Icon Link](https://github.com/bartzaalberg/php-tester/blob/master/data/icons/128/com.github.bartzaalberg.php-tester.svg)

- [x] **Prettifier**
- Comment=Prettify your JSON/XML outputs
- Icon=com.github.fleury08.prettifier
- Note: [Icon Link](https://appstream.elementary.io/appcenter/media/bionic/com/github/fleury08.prettifier/95F5FD1CD7C1DBE03B38077691E5B235/icons/64x64/com.github.fleury08.prettifier_com.github.fleury08.prettifier.png)

- [x] **Shutdown Scheduler**
- Comment=Schedule your computer's shutdown easily
- Icon=com.github.bcedu.shutdownscheduler
- Note: [Icon Link](https://github.com/bcedu/ShutdownScheduler/blob/master/data/icons/com.github.bcedu.shutdownscheduler.svg)

- [x] **Tranqil**
- Comment=Relax to soothing sounds of nature
- Icon=tranquil **and** com.github.nick92.tranqil
- Note: [Icon Link](https://github.com/nick92/tranqil/blob/master/data/icons/128/tranquil.svg)

- [x] **Translator**
- Comment=Simple and fast translator
- Icon=com.github.rapidfingers.translator
- Note: [Icon Link](https://github.com/RapidFingers/Translator/blob/master/data/translator_raw.svg)

- [x] **Webpin**
- Comment=A simple app to pin websites on the desktop
- Icon=com.github.artemanufrij.webpin
- Note: [Icon Link](https://github.com/artemanufrij/webpin/blob/master/data/icons/64/com.github.artemanufrij.webpin.svg)

- [x] **Yishu**
- Comment=A bespoke and simple Todo.txt client
- Icon=com.github.lainsce.yishu
- Note: [Icon Link](https://github.com/lainsce/yishu/blob/master/data/icons/128/com.github.lainsce.yishu.svg)

**Comment by btd1337** [comment]
@cbrnix Thank you for your excellent work!

**Comment by cbrnix** [comment]
> @cbrnix Thank you for your excellent work!

You welcome)
