### ISSUE TITLE
Weird window buttons

### ISSUE THREAD

**Issue by ginwsby** [cbrnix/Newaita#35]
Hi, i've install the latest RC 1.2.1, and I see lot of things are changed. Generally, i don't like when the icon theme customize the window buttons, so, how can I use the default?
Thanks!
![schermata da 2018-11-18 09-43-37](https://user-images.githubusercontent.com/20545323/48670422-f1e6a580-eb17-11e8-9066-1367b63a4a3c.png)

**Comment by cbrnix** [comment]
find and delete the icon in /actions /symbolic
This should help

**Comment by ginwsby** [comment]
I tried, but the icon has completely disappeared, I had to reinstall the theme.

**Comment by cbrnix** [comment]
The icon disappeared because the cache was not updated.

**Comment by ginwsby** [comment]
i tried with sudo gtk-update-icon-cache but nothing change. this is what i get
![schermata da 2018-11-18 18-38-09](https://user-images.githubusercontent.com/20545323/48676044-48c49d00-eb61-11e8-8d58-c50f162bfb39.png)

**Comment by cbrnix** [comment]
The cache of the gtk theme should be updated, not the icons. Give a link to this theme.

**Comment by ginwsby** [comment]
this is materia-theme(https://github.com/nana-4/materia-theme), but i tried with different themes, the result is the same.

**Comment by cbrnix** [comment]
When changing the theme of the icons something changes?
I made new icons for the window, try them. For the next two days I don’t have much opportunity to devote time to a separate problem. At the weekend, see what you can do

**Comment by btd1337** [comment]
@cbrnix Would it be possible to draw the softest strokes? They seem to be blurred.

Compare to the search icon's thickness.

**Newaita**
![captura de tela de 2018-11-18 19-51-08](https://user-images.githubusercontent.com/11943860/48678557-0b194180-eb6c-11e8-8621-618a4bc1e43d.png)

**Papirus**
![captura de tela de 2018-11-18 19-51-46](https://user-images.githubusercontent.com/11943860/48678559-110f2280-eb6c-11e8-857d-3e5379b90e81.png)

**Newaita**
![captura de tela de 2018-11-18 20-04-52](https://user-images.githubusercontent.com/11943860/48678663-6c8de000-eb6d-11e8-86ec-8001a2811cde.png)

**Papirus**
![captura de tela de 2018-11-18 20-05-19](https://user-images.githubusercontent.com/11943860/48678676-93e4ad00-eb6d-11e8-9aff-6584b075c54a.png)
