### ISSUE TITLE
icons request

### ISSUE THREAD

**Issue by geison-muniz** [cbrnix/Newaita#36]
@cbrnix First, congratulations on this excellent work.

You're contributing to a better linux community!

Could you add these icons to your theme?

---

## Adobe Suite 

**Application:** Adobe Photoshop
**icon:** photoshop | AdobePhotoshop 
[better svg icon](https://www.iconfinder.com/icons/1785889/adobe_cloud_creative_editor_graphics_photoshop_raster_icon) 

**Application:** Adobe Illustrator
**icon:** illustrator | AdobeIllustrator
[better svg icon](https://www.iconfinder.com/icons/1785895/adobe_cc_cloud_creative_illustrator_icon) 

**Application:** Adobe Lightroom
**icon:** lightroom | AdobeLightroom
[better svg icon](https://www.iconfinder.com/icons/1785892/adobe_cc_cloud_creative_lightroom_lr_icon) 

**Application:** Adobe Fireworks
**icon:** fireworks | AdobeFireworks
[better svg icon](https://www.iconfinder.com/icons/1785889/adobe_cloud_creative_editor_graphics_photoshop_raster_icon) 

[amazing mimetypes for adobe suite](http://www.iconarchive.com/show/aquave-adobe-cc-icons-by-thebassment.html)

All these Adobe applications are available on PlayOnLinux

---

**Application:** Figma
**icon:** figma | figma-linux
[svg icon](https://www.iconfinder.com/icons/2745006/design_figma_product_prototyping_soft_icon) 

---

## Jetbrains Suite

**Application:** Appcode
**icon:** appcode
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/appcode-icon.html) 

**Application:** Clion
**icon:** clion
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/clion-icon.html) 

**Application:** GoLand
**icon:** goland
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/goland-icon.html) 

**Application:** PhpStorm
**icon:** phpstorm
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/phpstorm-icon.html) 

**Application:** Resharper
**icon:** resharper
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/resharper-icon.html) 

**Application:** ResharperCPP
**icon:** resharper-cpp
[svg icon](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fblog.jetbrains.com%2Fclion%2Ffiles%2F2017%2F01%2FR_400x400_Twitter_logo_white.png&f=1) 

**Application:** RubyMine
**icon:** rubymine
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/rubymine-icon.html) 

**Application:** WebStorm
**icon:** webstorm
[svg icon](http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/webstorm-icon.html) 

---

I will leave these beautiful icons of inspiration to your Filetypes: https://www.flaticon.com/packs/file-types

Thank you in advance!

**Comment by cbrnix** [comment]
> PS: My window maximization icon and window restore icon are the same
> 
> Is this normal?

try gtk-update-icon-cache ./ in Newaita dir

**Comment by cbrnix** [comment]
Done
