### ISSUE TITLE
By default, Newaita (light version) displays grey folders...

### ISSUE THREAD

**Issue by asqwerth** [cbrnix/Newaita#37]
... not the actual default envelope-brown coloured folders.  I have to run the FV.sh script in Newaita to get the default brown folder colour.

Is this intentional or a bug?  

For Newaita-dark, the correct default colour folders are displayed out of the box.

For your information: I extracted the light and dark icon sets manually into $HOME/.icons folder.

Apart from that, I love this icon theme!  Excellent work, beautiful and fine detailing on all the icons.

On another note, can I ask for clarification of the licence terms in the Issues page? Or should I contact you separately?

**Comment by cbrnix** [comment]
This is unintended. Apparently, I tested the script and just forgot XD

For the license you can email me:
  ghostdmn2@gmail.com
