### ISSUE TITLE
Icon requests (2)

### ISSUE THREAD

**Issue by asqwerth** [cbrnix/Newaita#38]
I know you are busy but will be grateful if you could make icons for or interpret the original logo/icons your way:

1) ksnip: this is a screenshot + editor/annotator program.  Love the program but the official logo doesn't match or go with any icon theme, to be honest.  

![ksniplogo](https://user-images.githubusercontent.com/22598625/48882996-845cb100-ee58-11e8-90b1-5aec8ab9b5dc.png)

https://www.opendesktop.org/s/Debian-Packages/p/1156408/

2) MX-Tools (icon for the main Toolbox)

![mx-tools-moka96x96](https://user-images.githubusercontent.com/22598625/48883117-31372e00-ee59-11e8-9c70-7317acd1022a.png)

https://mxlinux.org/sites/default/files/mxtools-icon-96.svg

**Comment by cbrnix** [comment]
done
