### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by 0pLuS0** [cbrnix/Newaita#4]
Hi,

I'm not sure if this is a issue in the icon set, or QtFM.

I don't know if you are familiar with QtFM, the original Author seems to have dropped, and someone else picked it up, and I've been playing around with the latest master;

```git clone https://github.com/rodlie/qtfm.git```

One thing I've noticed so far with two iconsets, is when I got to the Settings, I get this message;

```libpng warning: iCCP: known incorrect sRGB profile```

So I wanted to pass this by you in case there was an incorrect sRGB profile in the icons some where, for you to correct it.

```P.S. I'm actually pretty sure there is an incorrect sRGB somewhere, because I had this happen in the past with an icon set that I've since corrected it on my end, and I tested that icon set in QtFM and I'm not getting this message```

**Comment by cbrnix** [comment]
No, my theme does not have png files. 
libpng 1.6 checks the profile in png and if it is incorrect it informs.

**Comment by 0pLuS0** [comment]
Does this look like your icons on the left pane?

![icon](https://user-images.githubusercontent.com/36190223/43107864-66e46116-8ece-11e8-9240-17d56796a5ed.jpg)

**Comment by cbrnix** [comment]
All my icons is svg files

**Comment by 0pLuS0** [comment]
I guess the app QtFM is somehow triggering this...

hmm
