### ISSUE TITLE
Latest Juno application icons Missing

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#40]
These are the last programs on the Juno version that are available and has no icons yet.

You're almost completing the collection ...

- [x] **Code**
- Comment=Code Editor
- Icon=io.elementary.code
- [Icon Link](https://github.com/elementary/code/blob/master/data/icons/128/io.elementary.code.svg)

- [x] **Aesop**
- Comment=The simplest PDF viewer around
- Icon=com.github.lainsce.aesop
- [Icon Link](https://github.com/lainsce/aesop/blob/master/data/icons/128/com.github.lainsce.aesop.svg)

- [x] **Beemy**
- Comment=A cute little Body Mass Index calculator
- Icon=com.github.lainsce.beemy
- [Icon Link](https://github.com/lainsce/beemy/blob/master/data/icons/128/com.github.lainsce.beemy.svg)

- [x] **Boiler**
- Comment=Control your kettle remotely
- Icon=com.github.tkashkin.boiler
- [Icon Link](https://github.com/tkashkin/Boiler/blob/master/modules/application/data/com.github.tkashkin.boiler.svg)

- [x] **Clairvoyant**
- Comment=Ask questions and get psychic answers from this fortune teller
- Icon=com.github.cassidyjames.clairvoyant
- [Icon Link](https://github.com/cassidyjames/clairvoyant/blob/master/data/icons/128.svg)

- [x] **Coin**
- Comment=Track the virtual currencies in real world currency value with this handy applet
- Icon=com.github.lainsce.coin
- [Icon Link](https://github.com/lainsce/coin/blob/master/data/icons/128/com.github.lainsce.coin.svg)

- [x] **Comic Sticks**
- Comment=Read xkcd: a webcomic of romance, sarcasm, math, and language
- Icon=com.github.rkoesters.xkcd-gtk
- [Icon Link](https://github.com/rkoesters/xkcd-gtk/blob/master/data/com.github.rkoesters.xkcd-gtk.svg)

- [x] **Desktop Folder**
- Comment=Bring your desktop back to life
- Icon=com.github.spheras.desktopfolder
- [Icon Link](https://github.com/spheras/desktopfolder/blob/master/data/icons/128/com.github.spheras.desktopfolder.svg)

- [x] **Eddy**
- Comment=Install and Manage .deb Files
- Icon=com.github.donadigo.eddy
- [Icon Link](https://github.com/donadigo/eddy/blob/master/data/icons/128/com.github.donadigo.eddy.svg)

- [x] **File Conflicts Finder**
- Comment=Helps to detect and solve possible file conflicts
- Icon=com.github.artemanufrij.findfileconflicts
- [Icon Link](https://github.com/artemanufrij/findfileconflicts/blob/master/data/icons/64/com.github.artemanufrij.findfileconflicts.svg)

- [x] **Haguichi**
- Comment=A graphical frontend for Hamachi
- Icon=com.github.ztefn.haguichi
- [Icon Link](https://github.com/ztefn/haguichi/blob/master/data/icons/elementary/hicolor/128x128/apps/com.github.ztefn.haguichi.svg)

- [x] **HostsManager**
- Comment=Manage your /etc/hosts file
- Icon=com.github.bbuhler.hostsmanager
- [Icon Link](https://github.com/bbuhler/HostsManager/blob/master/data/icons/128/com.github.bbuhler.hostsmanager.svg)

- [x] **Image Optimizer**
- Comment=Simple lossless image compression
- Icon=com.github.gijsgoudzwaard.image-optimizer
- [Icon Link](https://github.com/GijsGoudzwaard/Image-Optimizer/blob/master/data/icons/128/com.github.gijsgoudzwaard.image-optimizer.svg)

- [x] **Lottery**
- Comment=A tool to determine who will be the winner
- Icon=com.github.bartzaalberg.lottery
- [Icon Link](https://github.com/bartzaalberg/lottery/blob/master/data/icons/128/com.github.bartzaalberg.lottery.svg)

- [x] **Luna**
- Comment=An amazing calendar widget
- Icon=com.github.calo001.luna
- [Icon Link](https://github.com/calo001/luna/blob/master/data/images/icons/128/com.github.calo001.luna.svg)

- [x] **Melody**
- Comment=A music player for listening local music files, online radios and Audio CD's
- Icon=com.github.artemanufrij.playmymusic
- [Icon Link](https://github.com/artemanufrij/playmymusic/blob/master/data/icons/64/com.github.artemanufrij.playmymusic.svg)

- [x] **Memories**
- Comment=Manage local image files
- Icon=com.github.artemanufrij.showmypictures
- [Icon Link](https://github.com/artemanufrij/showmypictures/blob/master/data/icons/48/com.github.artemanufrij.showmypictures.svg)

- [x] **Metronome**
- Comment=A simple metronome for all musicians
- Icon=com.github.artemanufrij.metronome
- [Icon Link](https://github.com/artemanufrij/metronome/blob/master/data/icons/48/com.github.artemanufrij.metronome.svg)

- [x] **Monitor**
- Comment=Display usage of system resources, filter and manage processes.
- Icon=com.github.stsdc.monitor
- [Icon Link](https://github.com/stsdc/monitor/blob/master/data/icons/128/com.github.stsdc.monitor.svg)

- [x] **Nimbus**
- Comment=See outside without going there
- Icon=com.github.danrabbit.nimbus
- [Icon Link](https://github.com/danrabbit/nimbus/blob/master/data/icons/128/com.github.danrabbit.nimbus.svg)

- [x] **Nino**
- Comment=A network monitor widget
- Icon=com.github.torikulhabib.nino
- [Icon Link](https://github.com/torikulhabib/nino/blob/master/data/icons/128.svg)

- [x] **Notejot**
- Comment=A stupidly-simple sticky notes application for any type of short term notes or ideas
- Icon=com.github.lainsce.notejot
- [Icon Link](https://github.com/lainsce/notejot/blob/master/data/icons/128/com.github.lainsce.notejot.svg)

- [x] **Notifier**
- Comment=Never forget to do something
- Icon=com.github.timecraft.notifier
- [Icon Link](https://github.com/Timecraft/notifier/blob/master/data/icons/128/com.github.timecraft.notifier.svg)

- [x] **Odysseus**
- Comment=Odysseus is a convenient and privacy-respecting web browser, that increasingly, gently, and unobtrusively guides you wherever you want to go online.
- Icon=com.github.alcinnz.odysseus
- [Icon Link](https://github.com/alcinnz/Odysseus/blob/master/data/icons/128/com.github.alcinnz.odysseus.svg)

- [x] **Pho**
- Comment=Pho for 4chan
- Icon=com.github.dcharles525.pho
- [Icon Link](https://github.com/dcharles525/pho/blob/master/data/icons/128/com.github.dcharles525.pho.svg)

- [x] **Pwned Checker**
- Comment=Check if your password has beed leaked
- Icon=com.github.plugarut.pwned-checker
- [Icon Link](https://github.com/PlugaruT/pwned-checker/blob/master/data/icons/128/com.github.plugarut.pwned-checker.svg)

- [x] **Quotes**
- Comment=Quotes for daily inspiration
- Icon=com.github.alonsoenrique.quotes
- [Icon Link](https://github.com/AlonsoEnrique/quotes/blob/master/data/images/icons/128/com.github.alonsoenrique.quotes.svg)

- [x] **Snaptastic**
- Comment=A manager for snaps
- Icon=com.github.bartzaalberg.snaptastic
- [Icon Link](https://github.com/bartzaalberg/snaptastic/blob/master/data/icons/128/com.github.bartzaalberg.snaptastic.svg)

- [x] **Tootle**
- Comment=Lightning fast client for Mastodon
- Icon=com.github.bleakgrey.tootle
- [Icon Link](https://github.com/bleakgrey/tootle/blob/master/data/icons/128/com.github.bleakgrey.tootle.svg)

- [x] **Translit**
- Comment=Translit is a simple method of encoding Cyrillic letters with Latin ones
- Icon=com.github.artemanufrij.translit
- [Icon Link](https://github.com/artemanufrij/translit/blob/master/data/icons/64/com.github.artemanufrij.translit.svg)

- [x] **Wallpaperize**
- Comment=Beautify your oddly-sized wallpapers
- Icon=com.github.philip-scott.wallpaperize
- [Icon Link](https://github.com/Philip-Scott/wallpaperize/blob/master/data/icons/128/com.github.philip-scott.wallpaperize.svg)

**Comment by cbrnix** [comment]
Done!

**Comment by btd1337** [comment]
Excellent job! Only one icon was missing.

**Comment by cbrnix** [comment]
> Excellent job! Only one icon was missing.

Well, now everything is exactly XD
