### ISSUE TITLE
Jetbrain product icons and dbeaver icon are bigger than others

### ISSUE THREAD

**Issue by ceyhunnabiyev** [cbrnix/Newaita#41]
![screenshot from 2018-11-28 20-20-32](https://user-images.githubusercontent.com/5506156/49165555-ec286580-f34a-11e8-9b63-9baa55e32990.png)

**Comment by btd1337** [comment]
@ceyhunnabiyev Rider and Dbeaver doesn't have icons any yet. You must ask them to be created.

See how: [Icon Request Template](https://github.com/cbrnix/Newaita/issues/28)

**Comment by cbrnix** [comment]
@ceyhunnabiyev 
Added: dbeaver-ee, dbeaver, rider
Please don't hurry next time. Better to make it comfortable for me. So you get the result faster :)

**Comment by ceyhunnabiyev** [comment]
Wow!! Thank you very much for the fast fixes..

> Please don't hurry next time. Better to make it comfortable for me. So you get the result faster :)

Ok :), sorry for that...
