### ISSUE TITLE
Update icon headphone and headset Ubuntu

### ISSUE THREAD

**Issue by guilherfp** [cbrnix/Newaita#44]
- Update current device headphones to headsets.

- Change headphones icon to:
![image](https://user-images.githubusercontent.com/2766675/49216520-6fc96d00-f3b2-11e8-8539-727324b7a090.png)

**Comment by cbrnix** [comment]
Does the difference between headphones and headset matter?

**Comment by guilherfp** [comment]
It helps a lot in the selection of the device.
![image](https://user-images.githubusercontent.com/2766675/49247487-8695b100-f3fe-11e8-85d6-52960ec26ede.png)

**Comment by cbrnix** [comment]
It is unlikely that the system makes a difference. Differences are only for bluetooth headset and normal

![default](https://user-images.githubusercontent.com/40643537/49247678-e86b1080-f428-11e8-85c5-56d38e85959a.png)

**Comment by cbrnix** [comment]
Try now. Not sure what the difference will be

**Comment by cbrnix** [comment]
That's what I wrote about. The system itself does not see the difference between them.

**Comment by btd1337** [comment]
An issue should be opened in the application repository so that its source code is adjusted to point to different icons.
