### ISSUE TITLE
Gnome notification icon is missing

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#50]
I don't know that icon this is but he is missing out on all gnome notification messages.

![captura de tela de 2018-12-08 13-32-04](https://user-images.githubusercontent.com/11943860/49687701-ea4e6700-faed-11e8-93d7-11edb17bf801.png)

![captura de tela de 2018-12-08 13-32-17](https://user-images.githubusercontent.com/11943860/49687704-f0dcde80-faed-11e8-8815-b662c6ee28c1.png)

![not1](https://user-images.githubusercontent.com/11943860/49687707-1833ab80-faee-11e8-95d4-7b2593b04e3b.png)

![not2](https://user-images.githubusercontent.com/11943860/49687710-1c5fc900-faee-11e8-845a-c09a613157ef.png)

**Comment by cbrnix** [comment]
In the gnome, in my opinion, there is no notification indicator. They are displayed ascent, and then when you hover on the clock. I may be wrong, but, like so

**Comment by btd1337** [comment]
I'll also try to identify if the icon is related to the GTK theme.

**Comment by cbrnix** [comment]
I found this, Done! :)

**Comment by btd1337** [comment]
Now...

![captura de tela de 2018-12-10 18-52-44](https://user-images.githubusercontent.com/11943860/49760979-e4eb4b00-fcac-11e8-99af-cac9097fe6e6.png)

I think that this icon is load on system startup when a notify was lost.

**Comment by btd1337** [comment]
@cbrnix this icon is missing now again.

**Comment by cbrnix** [comment]
While vulnul old. Now working on new icons actions that will be monochrome

**Comment by btd1337** [comment]
It not solved for me
![Captura de tela de 2019-04-01 21-01-19](https://user-images.githubusercontent.com/11943860/55367048-93680580-54c1-11e9-9413-fd0bef0804e4.png)

**Comment by 73** [comment]
This should not be an envelope. It should look like ⬤. 
When I was looking into it, I also found this Issue:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1439

**Comment by cbrnix** [comment]
> This should not be an envelope. It should look like ⬤.
> When I was looking into it, I also found this Issue:
> https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1439
> 
> Should I open a new Issue for: "Notification Icon should not be an envelope" ?
Why did you decide that there should be a point?  Because the developer Adwaita did this?

**Comment by 73** [comment]
That is a good question! Should it be an envelope?

**Comment by cbrnix** [comment]
> That is a good question! Should it be an envelope?

A notification is a message from the system, isn't it?  And for messages, what could be more understandable than an envelope?

**Comment by 73** [comment]
Point taken. Event though I don't like it.
The turquoise envelope does look out of place. 
Maybe, I just replace it on my side. 

I can not let go of your theme, the app icons are just so beautiful!

**Comment by cbrnix** [comment]
In any case, I would recommend for Gnome to remove all symbolic icons.

**Comment by 73** [comment]
You mean like in #144?

**Comment by cbrnix** [comment]
> You mean like in #144?

Yeah. Try it

**Comment by 73** [comment]
That reflects my current settings.

**Comment by cbrnix** [comment]
I have not yet figured out how to make monochrome icons harmonious in Gnome and KDE.  Most likely, I will make icons thicker for Gnome

**Comment by 73** [comment]
That would be lovely. If you will release something especially for GNOME, I can mange to get on with my turquoise envelope ;) Thank you so much for humoring me, again.
