### ISSUE TITLE
In dash-to-dock Newaita icon size is small

### ISSUE THREAD

**Issue by ceyhunnabiyev** [cbrnix/Newaita#52]
Look at the difference:

Newaita
![screenshot from 2018-12-13 10-37-56](https://user-images.githubusercontent.com/5506156/49920368-6fa59300-fec3-11e8-9007-a9f4eecd146c.png)

Papirus
![screenshot from 2018-12-13 10-36-30](https://user-images.githubusercontent.com/5506156/49920392-7f24dc00-fec3-11e8-9878-9697c07ea537.png)
It doesn't matter which icon size is selected in dash-to-dock settings.

**Comment by btd1337** [comment]
What size you set to Dash to Dock icons?

![captura de tela de 2018-12-13 15-53-00](https://user-images.githubusercontent.com/11943860/49957582-6e8a5b00-feef-11e8-8e72-97caf7f419d3.png)

**Comment by ceyhunnabiyev** [comment]
13px

**Comment by cbrnix** [comment]
Squeeze the dock and increase its size. The dock should be bigger. For this he is needed)

**Comment by ceyhunnabiyev** [comment]
This is not my issue answer. Ok, no problem, Closed.

**Comment by cbrnix** [comment]
> This is not my issue answer. Ok, no problem, Closed.

This is not a bug. Icons take up less space than papyrus
