### ISSUE TITLE
[Doubt] Memory Ram icon

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#57]
@cbrnix Could you ask me a question?

Is the [ram memory icon](https://github.com/cbrnix/Newaita/blob/master/Newaita/devices/64/media-memory.svg) displaying a CPU?

**Comment by cbrnix** [comment]
she will be different

**Comment by btd1337** [comment]
The new icon looks great!

Your work is getting better every day. Congratulations on your talent!

**Comment by cbrnix** [comment]
Thank you very much. I wish it were true XD
