### ISSUE TITLE
Fedora system often hangs and signals seem to loop (e.g. keyboard input repeating)

### ISSUE THREAD

**Issue by yerbestpal** [cbrnix/Newaita#59]
Odd bug to file for an icon set but it only occurs when using it. As mentioned, the mouse and UI often hangs and stutters and keyboard input repeats causing all sorts of issues.

**Comment by cbrnix** [comment]
These symptoms are very similar to problems with the video driver. Practically, it is possible that the icons are to blame. Rather, this is due to the fact that the driver renders svg badly

**Comment by yerbestpal** [comment]
The issue no longer seems to occur.
