### ISSUE TITLE
Terminal icon does not seem to scale

### ISSUE THREAD

**Issue by 73** [cbrnix/Newaita#60]
Hi All,
nice icon theme you have here.
I have the issue shown in the screenshot:
![screenshot](https://user-images.githubusercontent.com/529346/52116166-c6506300-2610-11e9-8908-f988e100156f.png)
The lover is `nautilus` the upper is `gnome-terminal`.

What can I do?
Thank you very much!

**Comment by cbrnix** [comment]
Strange, did not notice such a problem on different systems. How will the replacement of my motherboard come - see what could be the problem

**Comment by 73** [comment]
If there are steps I can take to help, let me know. I don't now much about
icon sets.

**Comment by 73** [comment]
This is not an Newaita issue. It happens with other icon sets, too.
