### ISSUE TITLE
Question: Gedit Iocn

### ISSUE THREAD

**Issue by PJSingh5000** [cbrnix/Newaita#61]
Firstly, let me say, this is a very beautiful icon theme, and you are very talented.

Newaita has become my standard gnome shell icon theme on Ubuntu. Thank you!

I'd like to politely aks you to take another look at the design of the gedit icon?...

The current dark icon seems to imply a more complex application (like an IDE), rather than the efficient, simple, and easy to use text editor that gedit is.

I also feel that the size of the icon should be a little larger.

I wonder if a variation on your `standard-notes.svg` icon may be better convey the spirit of gedit?

Here is an example. (I used red to evoke the gedit branding color as shown on https://wiki.gnome.org/Apps/Gedit).

![new_gedit svg](https://user-images.githubusercontent.com/19394936/52187882-d6796580-27fd-11e9-8188-c7b112d6806c.png)

If you do decide to revisit this icon, may be you can come up with a better way to capture the "sprit" of gedit than my attempt above?

Thanks, once again, for the great theme!

**Comment by cbrnix** [comment]
Have you seen Gedit in the dark version with a grid? He's beautiful :)
