### ISSUE TITLE
pamac icon should change to the shield when you have no updates. ( I think )

### ISSUE THREAD

**Issue by freefreeno** [cbrnix/Newaita#65]
I think the pamac icon is supposed to be like this when there is no updates.
![screenshot_2019-02-23_21-45-44](https://user-images.githubusercontent.com/41884680/53294848-a1d14c00-37b4-11e9-8a5b-49134be354e4.png)

But with your icons it stays like this all the time.
![screenshot_2019-02-23_21-48-31](https://user-images.githubusercontent.com/41884680/53294862-cf1dfa00-37b4-11e9-95a7-54f35a5acef3.png)
 It is not a big deal but I do think there is a method to it.

**Comment by cbrnix** [comment]
Is it possible to implement in some way?
