### ISSUE TITLE
Unreal Engine Editor Icon

### ISSUE THREAD

**Issue by AdsonCicilioti** [cbrnix/Newaita#66]
Since you already have the Unity editor icon, you could have the Unreal Engine Editor icon.
I'm using it currently. It runs incredibly well in linux .. All it needs is a good icon.

**Comment by cbrnix** [comment]
Added unrealengine. Unfortunately, I can not see what kind of icon desktop requests

**Comment by AdsonCicilioti** [comment]
https://docs.unrealengine.com/en-us/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow

**Comment by cbrnix** [comment]
You can find the .desktop file of this application and look there in line
icon =
?
Usually in .local/share/applications or /usr/share/applications

**Comment by AdsonCicilioti** [comment]
I'm not using Linux on moment, but i'll investigate on Unreal Source repository.

**Comment by cbrnix** [comment]
UE4Editor added
