### ISSUE TITLE
[ Discussion ] Change design of dropbox status icons

### ISSUE THREAD

**Issue by otavioschwanck** [cbrnix/Newaita#67]
This icon theme is the most beutiful on linux world (personal opinion), but the Dropbox status are a little ugly:

![image](https://user-images.githubusercontent.com/9551316/53614644-67531f00-3bb9-11e9-8a0e-43e9d7dd4444.png)

Maybe would be nice if this icon are a little smaller.

**Comment by cbrnix** [comment]
I have changed, but in gnome they are so big. In KDE, let's say, there is not much space for them and they are not so striking.
