### ISSUE TITLE
Slack icon out of date

### ISSUE THREAD

**Issue by beanaroo** [cbrnix/Newaita#69]
Hi there!

First of all, thanks for the amazing work!

Slack have [rebranded](https://slackhq.com/say-hello-new-logo) their icon and I thought an update may be needed.
![New Logo](https://slackhq.com/wp-content/uploads/2019/01/2019-01_BrandRefresh_slack-brand-refresh_04-harmonized-logos.png)

**Comment by cbrnix** [comment]
Added

**Comment by cbrnix** [comment]
OMG. I added slack to places... Overworked XD 
Fixed
