### ISSUE TITLE
Evolution: few icons missing

### ISSUE THREAD

**Issue by danjac** [cbrnix/Newaita#72]
Awesome work on this great icon set!

I noticed a few Evolution icons still missing particularly in the calendar area. The first is when creating a new Appointment, the second in the "todo" list on the right hand side of the default screen:

![Screenshot from 2019-03-10 13-53-13](https://user-images.githubusercontent.com/249779/54084658-2c30b880-433c-11e9-93c8-11bd35f267ed.png)

![Screenshot from 2019-03-10 13-52-44](https://user-images.githubusercontent.com/249779/54084659-2e931280-433c-11e9-9e48-9303f5c8a1be.png)

**Comment by cbrnix** [comment]
Be patient. I will change all the characters Aсtions on monochrome and more concise. At the same time I will supplement them

**Comment by cbrnix** [comment]
Evolution complete XD
