### ISSUE TITLE
Can i use an icon from here as my app's defaut icon?

### ISSUE THREAD

**Issue by maoschanz** [cbrnix/Newaita#74]
Hi, i've just seen this https://github.com/cbrnix/Newaita/blob/47281bcac7af1b2d02c2f6f5d6ec3b9e9127f138/Newaita/apps/64/com.github.maoschanz.Drawing.svg and it's really beautiful. Since i'm not able to do a good icon myself, i wondered if i could use it as the default icon for this application.

**Comment by cbrnix** [comment]
Yes, no problem, if you want, I will send you a larger one.

**Comment by cbrnix** [comment]
Be patient for a while, please. After about a week, I’ll update where the new action symbolic will be, then I’ll change all action icons to monochrome and more expressive ones.

**Comment by maoschanz** [comment]
Amazing, thanks you. Should i add just "Dmitry Z." in the credits or do you want your full name?

**Comment by cbrnix** [comment]
> Amazing, thanks you. Should i add just "Dmitry Z." in the credits or do you want your full name?

Yes, whatever you want. I'm not conceited xD

**Comment by cbrnix** [comment]
128, 256, 512 if you want

[Icon.zip](https://github.com/cbrnix/Newaita/files/2956774/Icon.zip)
