### ISSUE TITLE
Dropbox tray icon is stretched

### ISSUE THREAD

**Issue by kkga** [cbrnix/Newaita#75]
I'm 100% sure that it's related to this specific icon set, however it does look normal when I change the icons to default.

![image](https://user-images.githubusercontent.com/1460122/54475069-2e908800-47fe-11e9-8e66-1c242985909a.png)

**Comment by cbrnix** [comment]
And if you put my topic and restart the session, the problem remains?

**Comment by kkga** [comment]
Yes, tried restarting via <kbd>Alt</kbd>+<kbd>F2</kbd> and typing `r` and also tried logging out -- still the same issue.

**Comment by cbrnix** [comment]
I will try to understand next weekend (19-20).
Do not really understand yet why this is happening

**Comment by kkga** [comment]
Can it be related to the extension I’m using for showing the icons?
I’m using this one https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by cbrnix** [comment]
Try it now. But I believe that the matter is in the extension settings. Icons are no different from others. Maybe he needs certain proportions?

**Comment by kkga** [comment]
Yeah, I see that you’ve updated the icon, but it’s still stretched for me.

Sorry for confusion, gonna dig into the extension I’m using. Thanks!
