### ISSUE TITLE
Icon for org.gnome.Terminal missing

### ISSUE THREAD

**Issue by purejava** [cbrnix/Newaita#76]
Hi,

on Arch linux the icon referenced is called **org.gnome.Terminal**
```
[ralph@fusion ~]$ grep Icon /usr/share/applications/org.gnome.Terminal.desktop 
Icon=org.gnome.Terminal
[ralph@fusion ~]$
```

There is no such reference in the package, so the Adwaita icon is displayed instead.

Kind regards,
Ralph

![Term](https://user-images.githubusercontent.com/1822238/54866857-a9ffb580-4d79-11e9-91ab-0e1df5d45f24.jpg)

**Comment by cbrnix** [comment]
Added

**Comment by purejava** [comment]
Thanks.
Re-installing the Arch package pulled the fix.
The icon is displayed now.
