### ISSUE TITLE
Fix Gnome Icons

### ISSUE THREAD

**Issue by btd1337** [cbrnix/Newaita#77]
The Gnome apps was renamed to org.gnome.appname and now they need are updated in Newaita.

![Captura de tela de 2019-03-24 00-44-37](https://user-images.githubusercontent.com/11943860/54874633-0b517400-4dce-11e9-8867-3e5cea86d84f.png)

**Comment by cbrnix** [comment]
They unified the name of the icons. This happened! XD I'll add links

**Comment by cbrnix** [comment]
Added links

**Comment by btd1337** [comment]
As always, great job!
