### ISSUE TITLE
Tilix icon is same as Terminal icon

### ISSUE THREAD

**Issue by alex285** [cbrnix/Newaita#78]
Tilix original icon
![com gexperts Tilix](https://user-images.githubusercontent.com/11244308/54912674-cb87ab00-4ef9-11e9-827b-1939d9f88a51.png)

SVG version:
https://github.com/gnunn1/tilix/tree/master/data/icons/hicolor/scalable/apps

**Comment by cbrnix** [comment]
Restyled :)
