### ISSUE TITLE
Missing icons: OCaml (.ml) and KeePassX (.kbdx)

### ISSUE THREAD

**Issue by macthecadillac** [cbrnix/Newaita#79]
I noticed that icons for OCaml source files (.ml) and KeePassX database files (.kbdx) are missing. Could you add those icons?

Great work on creating this icon set by the way. I really enjoy it.

**Comment by cbrnix** [comment]
Unfortunately, I do not use them. Can you drop two such files so that I can see the mimetypes?

**Comment by macthecadillac** [comment]
That is understandable. There you go:
[MIME_Samples.tar.gz](https://github.com/cbrnix/Newaita/files/3027108/MIME_Samples.tar.gz)

I tarred them since GitHub doesn't support dropping these files directly.

**Comment by cbrnix** [comment]
Wait, these files are defined as text and empty. Mimetypes for them should be drawn.
![изображение](https://user-images.githubusercontent.com/40643537/55294705-f4360600-540d-11e9-8d63-cc30b01a0cee.png)

**Comment by macthecadillac** [comment]
.ml files are source code files of OCaml so they are really just text files. I guess whichever way you made it work for other kinds of source files (such as Python or Rust) should work here.

As for .kdbx files, I don't know how to help with that since the file I dropped earlier was directly generated by KeePassX. Dolphin seems to able to recognize them on my machine though.

![dolphin](https://user-images.githubusercontent.com/20234373/55295981-3b010d00-53c8-11e9-9dd2-fd858a42eed0.png)

**Comment by cbrnix** [comment]
Done. Check pls

**Comment by macthecadillac** [comment]
The icon for OCaml is kinda cute :). The KeePassX database icons are still missing but I guess that's about what we can do now.

**Comment by cbrnix** [comment]
The KeePassX should be reflected. Perhaps just cache problems

**Comment by cbrnix** [comment]
Oh... Added application-x-keepassx now

**Comment by macthecadillac** [comment]
Also symlink it to application-x-keepassxc so that icons on systems with KeePassXC (a KeePassX fork) will display properly (that was the reason your fix didn't work on my system).

**Comment by cbrnix** [comment]
added
