### ISSUE TITLE
borrow the indicator icons from another set (like Papirus)

### ISSUE THREAD

**Issue by gmlshadi** [cbrnix/Newaita#8]
![image](https://user-images.githubusercontent.com/11833878/45259464-5aa5f900-b3d6-11e8-9dfa-40c6180c4626.png)

![image](https://user-images.githubusercontent.com/11833878/45259474-8c1ec480-b3d6-11e8-9971-1824c412f1a1.png)

Other sets already have the appropriate icons for these indicators. Can you just copy them into your icon set?

**Comment by cbrnix** [comment]
Due to the differences in licensing agreements, I can not do this. I will make monochrome icons for the panel for individual applications

**Comment by cbrnix** [comment]
bear with it a little. The next update will consist of a panel of icons. I have already started drawing them
