### ISSUE TITLE
Symlinks for some flatpak applications

### ISSUE THREAD

**Issue by ubluish** [cbrnix/Newaita#82]
- [x] org.codeblocks.codeblocks
- [x] com.adobe.Flash-Player-Projector
- [x] org.libreoffice.LibreOffice.base
- [x] org.libreoffice.LibreOffice.calc
- [x] org.libreoffice.LibreOffice.writer
- [x] org.libreoffice.LibreOffice.draw
- [x] org.libreoffice.LibreOffice.impress
- [x] org.libreoffice.LibreOffice.math
- [x] org.libreoffice.LibreOffice.startcenter

**Comment by cbrnix** [comment]
Why do you point to libreoffice symlinks? They have long been there.

**Comment by ubluish** [comment]
The current theme symlinks for libreoffice using dash ' - ' before the type like `LibreOffice-writer` while the current icon name used in .desktop file version 6.2.2 is using dot ' . ' like `LibreOffice.writer`

**Comment by cbrnix** [comment]
Agree

**Comment by cbrnix** [comment]
Added

**Comment by ubluish** [comment]
Thanks alot
