### ISSUE TITLE
Icon Request: Fragments

### ISSUE THREAD

**Issue by ubluish** [cbrnix/Newaita#83]
- Application name: Fragments
- Icon name: `de.haeckerfelix.Fragments`
- Icon: 
![de haeckerfelix Fragments](https://user-images.githubusercontent.com/21042432/55496266-f03cfa80-563e-11e9-84ee-6287cdb7cde4.png)

**Comment by cbrnix** [comment]
Added

**Comment by ubluish** [comment]
Thanks alot for this awesome icon theme
