### ISSUE TITLE
Icon Request: SuperTuxKart

### ISSUE THREAD

**Issue by ubluish** [cbrnix/Newaita#86]
Application Name: SuperTuxKart
Flatpak Icon name: `net.supertuxkart.SuperTuxKart`
Normal icon name: `supertuxkart`
Icon:
![net supertuxkart SuperTuxKart](https://user-images.githubusercontent.com/21042432/55581858-35842980-571e-11e9-8d7f-a8abe2e5c3ba.png)

**Comment by cbrnix** [comment]
Added
