### ISSUE TITLE
Icon Request: Codeblocks mimetypes

### ISSUE THREAD

**Issue by ubluish** [cbrnix/Newaita#88]
**App Name:** codeblocks

- [x]  `application-x-codeblocks`
![application-x-codeblocks](https://user-images.githubusercontent.com/21042432/46911640-761a9b80-cf62-11e8-9833-dbd8cf2acc48.png)

- [x] `application-x-codeblocks-workspace`
![application-x-codeblocks-workspace](https://user-images.githubusercontent.com/21042432/46911642-7ca91300-cf62-11e8-8074-925bb973e6b9.png)

**Comment by cbrnix** [comment]
Added
