### ISSUE TITLE
(Opinion) These last changes icons screen locking and display's.

### ISSUE THREAD

**Issue by freefreeno** [cbrnix/Newaita#89]
First off I love this set. I have used it since it first came out and I have promoted the crap out of it also. I just do not think these last changes to the screen locking and displays icons look as good as the way they were. Like I said my opinion. Thanks for your hard work. I still like the icons but I will have to use old set I guess.

**Comment by cbrnix** [comment]
You can not even imagine how many opposing opinions I get about these or other changes. Moreover, on the individual icons. If we take into account everything that everyone who receives these icons wants, I will have to make at least 20 themes of icons. It does not speed up the work on them. Quite the contrary. I do not demand anything in return. Opensource assumes that the product is provided as is. If possible, I try to take into account the wishes of users, but I have my own opinion on the theme of icons.
