### ISSUE TITLE
Please rework emblems

### ISSUE THREAD

**Issue by germanfr** [cbrnix/Newaita#90]
They don't fit with the rest of icons. At first I thought there was something wrong or that they were broken. Here's an example of `emblem-package`.

* **This is how they currently look:**
![Screenshot from 2019-04-07 13-21-34](https://user-images.githubusercontent.com/10391266/55682771-1d87f200-5938-11e9-903a-b061a1cdca10.png)

* **I'd like them to look something more like this (from Adwaita):**
![Screenshot from 2019-04-07 13-20-43](https://user-images.githubusercontent.com/10391266/55682772-1e208880-5938-11e9-8fa1-f9c73a20e91a.png)

Thanks!

**Comment by cbrnix** [comment]
There is no error. These icons are made specifically such. Just like other emblems

**Comment by germanfr** [comment]
Yes, emblems are consistent between them but not with non-emblem icons (look at the screenshot).
I'd like them to be full-color and more newaita-like.

**Comment by cbrnix** [comment]
Maybe in the future. Now I am concerned about the actions
