### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by goransimic92** [cbrnix/Newaita#95]
Please symlink these app icons.

* [x]  **Brave Browser**
* Name=brave.svg
* Symlink=brave-browser.svg

* [x]  **GitKraken**
* Name=gitkraken.svg
* Symlink=com.axosoft.GitKraken.svg

* [x]  **Postman**
* Name=postman.svg
* Symlink=com.getpostman.Postman.svg

**Comment by cbrnix** [comment]
Added

**Comment by goransimic92** [comment]
Great, thanks.
