### ISSUE TITLE
White wifi network manager icon issue with default Adwaita theme

### ISSUE THREAD

**Issue by orschiro** [cbrnix/Newaita#96]
Can anyone confirm the below issue with the wifi network manager icon not showing properly because it's white on white panel background?

![Peek 2019-05-03 08-42](https://user-images.githubusercontent.com/170947/57122814-8c156f80-6d7f-11e9-8742-fa84213f1a83.gif)

**Comment by cbrnix** [comment]
use ./PV.sh script

**Comment by orschiro** [comment]
@cbrnix thanks!
