### ISSUE TITLE
Question regarding the icons in the Newaita spec folder.

### ISSUE THREAD

**Issue by freefreeno** [cbrnix/Newaita#97]
I am a fan of your work as you already know from me bugging you to death. I want to use the folder colors that are in the Newata-spec folder. How? They are so cool but I don't understand. Please fill me in. Also I know this is a lot to ask but I would love to see some folders in this green #6f7f69 or somewhere close. I used your folder colors already to model a lot of Plasma color schemes from and I have a very cool camo color scheme with no folders to match so maybe even make some camo folders. I already have one color scheme that uses your colors . Materia-Manjaro and it is very popular. My camo one has #3a3d39 plus the color up top. I really just came here to ask about spec folders but since I was here. lol Thanks for your hard work.

**Comment by cbrnix** [comment]
just extract all files of Special (including hidden ones) to the folder with Newaita or Newaita-dark
after this in the Newaita folder, run the script FV-spec.sh
As for your colors, I cannot promise in the near future. Vacation is over and very little time has become'(. And have to finish the main theme (there is still a lot to do)

**Comment by freefreeno** [comment]
Thanks for the reply. I can't even imagine how much time it takes for icon themes. I can barely manage regular Plasma theme. I figured it out and like you said it wasn't hard. Just for instance to give you an idea here is a screenshot of one of your icons with the highlighted green and it looks good but of course opinions are opinions and I really appreciate your work. I would love to see a plasma theme and color scheme form you in the furture. Just have a look at the highlighted icon just for reference on how it would look. The one by mouse pointer and thanks again. Don't work to hard.

![Screenshot_20190505_150026](https://user-images.githubusercontent.com/41884680/57199812-3ab8dc00-6f49-11e9-8e14-93c87f07b770.png)

**Comment by cbrnix** [comment]
I added Khaki with your color

**Comment by freefreeno** [comment]
Thanks. One thing about me I post themes daily even sometimes more then 1 and n every post I link your icons so maybe I am helping you a little also. I know me linking your stuff is in no way me actually helping you but you know I am like a commercial that will just not stop playing. lol

**Comment by cbrnix** [comment]
Which file manager do you mean?

**Comment by freefreeno** [comment]
Dolphin,konsole and chromium is the only colored icons on my panel and Konsole is black so it isn't that bad but the purple file manager icon and blue chromium icon kinda don't blend in well with the others.

**Comment by cbrnix** [comment]
It is hardly possible to make a monochrome application icon, if it is not for the tray. Otherwise, it will be monochrome for all sections. Only for tray icons are separated

**Comment by freefreeno** [comment]
Oh OK it has to be permanent for the panel to be mono then ?

**Comment by cbrnix** [comment]
Perhaps this is actually done by adding icons to the plasma theme, but I have not tried, to be honest
